### ISSUE TITLE
Local video stream has a slight lag

### ISSUE THREAD

**Issue by chrisse27** [microsoft/MixedReality-WebRTC#100]
1. Start the Video Chat Demo in the Unity editor on a Windows desktop
2. Observe the captured video in the local peer window

IS: the captured video has a slight lag, i.e. when I move my hand I can see the movement happening a tiny bit later in Unity. In contrast, when I look at the captured video in the Camera app of Windows I do not see such a lag.
SHOULD: have (almost) no lag

**Comment by djee-ms** [comment]
Possible hints:
- Are you running in Release?
- The Unity Editor is an editing app, not an end user product; you cannot really compare performance there, as the Editor likely induces some extra cost over a shipped product.
- There are known improvements and optimizations that need to be made in the WebRTC UWP code for video capture and encoding that MixedReality-WebRTC currently consumes. Work on this has just started.
- The WebRTC architecture is not designed for optimizing local video playback, although I do agree there should be almost no lag anyway; the current playback pipeline is much longer than it could be (see above point) but is anyway optimized architecturally to deliver frames to the remote peer and minimize that latency. Comparing with the Camera app of Windows which does only local playback is not really fair IMHO.

There is also some on-going work about external track support (see #35 for example), which would allow using an external capture pipeline with integrated local playback, which should get latency similar to the Camera app.

**Comment by chrisse27** [comment]
@djee-ms Thank you for the response. It actually was only a matter of setting the max video frame rate in the media player to 60 instead of 30.

**Comment by djee-ms** [comment]
Oh right, I forgot about that one! Glad that's fixed. 👍

**Comment by cundeger** [comment]
Hi,

I have a similar issue but more than a slight lag. I am trying webrtc among 2 computers. One of them is a desktop PC and the other is laptop PC. There are huge delays in webcam and received video images in laptop. Even, laptop shows its own local webcam video in a 1-2 seconds delay (cannot understand how?), but the desktop gets laptops webcam image much faster (almost no delay) than the loptop shows its own webcam (with 1-2 seconds). This is very interesting. I suspect VideoRenderer has a lag since there are the same delays in both local and receiver images where VideoRenderer is the shared component among these two. The frame rate of video renderer is 30 as default. I do not think problem is with communication since image is received in desktop PC with out any delay.

Best regards
