### ISSUE TITLE
WebGL support

### ISSUE THREAD

**Issue by JoelFrutiger** [microsoft/MixedReality-WebRTC#118]
Hello, are there any plans to add support for Unity WebGL builds? Or is there another method, I would like to display the stream on a website.

**Comment by djee-ms** [comment]
No there's no plan to support Unity WebGL. I think most devs who want to integrate with a website will directly use a web-based peer implementation. Since WebRTC is standardized, the only remaining part to figure out is a signalling method that works with a browser, generally based on WebSocket. So Unity WebGL has little value in my opinion.

**Comment by JoelFrutiger** [comment]
Okay, thanks I appreciate it.

About the signaling, would simple ajax calls and node-dss work in this case? Or do I need to look for a different signaling solution. Just trying to do a proof of concept.

**Comment by djee-ms** [comment]
Yes `node-dss` and AJAX should work. The `node-dss` protocol is ultra simplistic.
