### ISSUE TITLE
Switching camera during connection

### ISSUE THREAD

**Issue by cy238** [microsoft/MixedReality-WebRTC#139]
Hello,

how do you change the camera device (and resolution/fps) during an active connection? For our current project we would like to implement a front/back camera switch.
From my understanding it should be possible to use`WebRTC.PeerConnection.RemoveLocalVideoTrack` and `WebRTC.PeerConnection.AddLocalVideoTrackAsync` which then triggers new sdp offers/answers. But I can't get it to work...

I'm targetting UWP and using the Unity components so my initial test was to simply disable and reenable `LocalVideoSource` with a keybind during the call. This calls the aforementioned remove and add functions.
The remove call works as expected. The connected app removes the video track, audio and data channels stay active. Unfortunately upon reactivation of the component, the connected app just dies with a fatal error and no stacktrace or log output.

Is this even supported yet?

**Comment by djee-ms** [comment]
Yes this is supported and shouldn't crash. I see 2 approaches to what I think you are trying to do:

1. Either create a single track with the front camera, and when pressing the "flip" button, remove that track and add a new track with the back camera. This works, and has the advantage to only use one of the 2 cameras at once, but might be slow to switch, as adding/removing tracks takes a full SDP renegotiations.

2. Create 2 tracks, and disable one of them. When pressing the "flip" button, disable the current one and enable the other one, and switch Unity to render the enabled one only. This is a lot faster, because tracks stay alive, and disabling a track requires just a quick inline bool to tell the remote peer it's disable, and no SDP exchange. Also disabled tracks do not consume any bandwidth. The downside is that the app will need to open both cameras and keep exclusive access to both of them at all time, because there is no simple way to keep a track active without have also an active video source (camera) for it.

I think you tried 1. One thing to note here is that because you need an SDP exchange, if you handle the "renegotiation needed" event by immediately sending a new offer, when you remove the first track this starts an SDP exchange, which is likely to **not** have completed by the time you try to add the new track (which also fires a "renegotiation needed" event). To work around that, see how TestAppUWP is temporarily skipping calls to CreateOffer() during the "renegotiation needed" event when it knows multiple events will be fired in a short amount of time:

https://github.com/microsoft/MixedReality-WebRTC/blob/8409ac1ed2f1d9657c51340184ea7ece6a5af8c1/examples/TestAppUwp/MainPage.xaml.cs#L1276-L1281

**Comment by cy238** [comment]
Thanks for your help.

Yes, I tried option 1. The problem was indeed related to the renegotiation and skipping it in that case solves the crash issue.

The only problem that persists is that the `PeerConnection.TrackAdded` and `TrackRemoved` events seem to be raised in the wrong order. When switching I get the `TrackAdded` event for the new track first and then `TrackRemoved` for the old track is called. Therefore `VideoSource.VideoStreamStarted` and `VideoStreamStopped` are also raised in that order causing the `MediaPlayer` not to play. Is this easily fixable in the library? Otherwise I can probably add a (slightly hacky) workaround for restarting the player after a track switch.

**Comment by djee-ms** [comment]
_A priori_ I don't think it's very easy to handle the generic case of N different tracks trying to play with the same `MediaPlayer` instance. I would rather recommend making a copy of it that you can adapt to your particular use case. `MediaPlayer` was designed for the common case of a single audio and a single video track.

**Comment by AtosNicoS** [comment]
I currently try to implement a mechanism to add or remove a video camera inside a call. 

If I use approach 1. and always add new tracks, the webrtc library will crash after adding/removing the camera ~ >10 times with a native excpetion. I found no solution for this. Also it is not possible to remove tracks, so the SDP message becomes very large. Maybe I missunderstood something here, but I found no better way.

With the approach 2. I can set and unset the videotrack of the transceiver. However when removing the track, the video is still shown on the other side, with a frozen screen. It is not black, as you wrote. Is there a way on the other side to detect that sending video has stopped (even though the track still exists) or resumed?

This should be a very common usecase, but I found no good documentation or samples about that. Could you please help?

**Comment by djee-ms** [comment]
> Also it is not possible to remove tracks

If you use the default SDP semantic (Universal Plan) then there's no track in SDP, only transceivers. And yes, you cannot remove them. That's why it's better to attach/detach tracks from transceivers.

> the video is still shown on the other side, with a frozen screen. It is not black, as you wrote. 

I am assuming the WebRTC transport does indeed sends a "video mute" signal, but the receiver doesn't know how to interpret that / doesn't handle it (we may even not expose that unfortunately, I can't remember), so just stops receiving frames and does nothing else, therefore whatever media render pipeline is there simply freeze on the last frame received. I am not 100% sure how to detect detached/muted video. As a dirty workaround you could try polling once in a while (every 500ms?) the "mute" (=="enabled") state of the video, and when found muted (which I assume will be exhibited) you can clear the target renderer.

**Comment by AtosNicoS** [comment]
How can I access the mute state? A `RemoteVideoTrack` has no mute Property. The `Enabled` Property does not work.

**Comment by djee-ms** [comment]
- _Mute_ and _enable_ are the same thing. Confusingly Google call them enable, and we reused the same terminology. Even more confusingly Unity has an unrelated "enable" concept for `MonoBehaviour`, which is generally mapped to create/destroy of native objects in the Unity library because Unity's "enable" really means "is that component's `Update()` stepped at all?" which is needed for most non-destroyed native objects.
- Only local (sender) tracks can be disabled. See [`LocalVideoTrack.Enabled`](https://github.com/microsoft/MixedReality-WebRTC/blob/8666f367e61fd478be5433b01939695a33f81d5b/libs/Microsoft.MixedReality.WebRTC/LocalVideoTrack.cs#L105-L124). If _that_ doesn't work, please log a separate issue about it. On Unity we handle the local tracks internally inside `MediaLine` so you need to access them via [`MediaLine.LocalTrack`](https://github.com/microsoft/MixedReality-WebRTC/blob/a721bdf311ecebbea757eb80222e08e7949a8d58/libs/unity/library/Runtime/Scripts/Media/MediaLine.cs#L132).
- To """mute""" a remote track (which is not really muting because the sender still sends data, but at least looks like it on the receiver side), just stop rendering it and discard the incoming data. In C# for example you detach the `I420AVideoFrameReady` event handler.

**Comment by AtosNicoS** [comment]
I have Client A & B. Now I set `LocalVideoTrack.Enabled = false` on Client A. How can I detect that on Client B? I understand that Client B cannot disable the remote track, as it is only receiving it. But how will Client B notice that disabled state?

**Comment by djee-ms** [comment]
I don't think we expose anything for detecting it because I don't remember how we'd do that. There is definitely a signal on the wire as I remember, because I could see very visibly the network usage drastically drops (at least for audio when I tested the mute feature), and I remember reading comments about it in Google's code, but I don't know where it's exposed in the Google API, sorry. I've only found this in the Google code, which makes me think of using a timeout as a workaround (the comment below is for the video encoder, so not directly related, but still):
```
    // If the time diff since last update is greater than |max_frame_diff_ms|,
    // video is considered paused/muted and the change is not included.
```

**Comment by AtosNicoS** [comment]
Ouuuuf what a workaround. That could work, I've tested it. The event only fires when there are incoming frames.

But can't we have this in the webrtc library itself? I mean this is a basic feature, turning video on and off.

**Comment by djee-ms** [comment]
Yes I guess. But I expected that the remote side would receive black frames, so would clear it's render content anyway. I'm surprised this is not the case.

**Comment by AtosNicoS** [comment]
I dont know. Would you mind to reopen this issue?

**Comment by djee-ms** [comment]
What you are asking for (detect mute) is unrelated to the current issue (hot-swap back and front camera).

**Comment by AtosNicoS** [comment]
See https://github.com/microsoft/MixedReality-WebRTC/issues/681
