### ISSUE TITLE
Redundant conversion to ARGB consumes a lot of CPU (HL2 cannot stream > 720p with hardware H.264)

### ISSUE THREAD

**Issue by fibann** [microsoft/MixedReality-WebRTC#151]
This is a regression starting from https://github.com/microsoft/MixedReality-WebRTC/commit/ab67d06c5ff3fe216ad63ac58d092773b1ace98a (so impacts releases starting from v1.0.1). It's not incredibly clear what's happening but the best guess is that adding the callbacks triggers the conversion of every frame to RGB, which starves the encoding thread.

This is going to be fixed as part of #152. If the RGB frames are not needed, a simple workaround is to revert the commit above.

**Comment by fibann** [comment]
Further experiments show that just reverting that commit won't fix the issue on latest master. So some other cause was introduced between that commit and now. Will investigate more.

**Comment by fibann** [comment]
Commit https://github.com/microsoft/MixedReality-WebRTC/commit/1050e497258fed79d2dc1dcf4557e99eea8b342b moved the offending callback to another file, so blindly reverting https://github.com/microsoft/MixedReality-WebRTC/commit/ab67d06c5ff3fe216ad63ac58d092773b1ace98a won't disable it. Cherry-pick https://github.com/fibann/MixedReality-WebRTC/commit/2ae2408629934035f0a6e7e10e0722e94df9c416 instead.

**Comment by fibann** [comment]
This has been fixed by #412 - video callbacks are now added only if there is at least one managed handler, so we don't waste cycles by default anymore.

**Comment by fibann** [comment]
#412 implemented the correct pattern in video sources but did not backport it to video tracks, so this is still open.

**Comment by kspark-scott** [comment]
@fibann Can you clarify whether this issue affects encoding, decoding, or both?  Your initial description here refers to starving the _encoding_ thread, but this also references issue #160 which looks like a problem triggered by inbound video.

I ask because we have an upcoming release of our product and are trying to decide whether to move to 2.0.0 for this release or wait until the next.  The performance benefit of this fix would likely mean we would move to 2.0.0 immediately, but would prefer not to incur the risk (however minimal) if there is no immediate benefit.

Thanks

**Comment by fibann** [comment]
@kspark-scott this affects both local and remote video (note that it's not directly related to _encoding_, as long as you have a local track - even if you are not streaming it - you'll get the performance hit).

While we recommend that you upgrade to 2.0 in general, you can simply cherry-pick https://github.com/fibann/MixedReality-WebRTC/commit/2ae2408629934035f0a6e7e10e0722e94df9c416 (as said above) to work around this issue on 1.0.3 (note anyway that with that change the ARGB32 frame events will not be fired at all).

**Comment by kspark-scott** [comment]
Perfect, thanks.
