### ISSUE TITLE
Is it possibile use it on raspberry pi?

### ISSUE THREAD

**Issue by aperrone** [microsoft/MixedReality-WebRTC#154]
hi at all!

I have a question:
is this library compatible with windows 10 iot?  someone has done tests by loading a uwp arm app on a Raspberry pi?

Thank you!!!
Alex

**Comment by djee-ms** [comment]
Hi @aperrone,

Raspberry Pi was never tested as far as I know. IoT is not really a major focus area, since there is little connection to Mixed Reality as far as I know. That being said, the UWP ARM build has nothing specific to HoloLens so I see no reason _a priori_ why this wouldn't work. But I haven't heard of anyone trying so far. Happy to hear about any feedback if you try. Although we are not in general committing to supporting non-MR related changes, I am still open to discuss any simple change, if needed, that could unlock this platform.

**Comment by djee-ms** [comment]
Closing as I believe the question was answered. Please feel free to reopen if there's anything else.
