### ISSUE TITLE
Microsoft.MixedReality.WebRTC.Native.dll not downloaded when using nuget 

### ISSUE THREAD

**Issue by smedasn** [microsoft/MixedReality-WebRTC#156]
The Microsoft.MixedReality.WebRTC.Native.dll is not downloaded when using the nuget package "Microsoft.MixedReality.WebRTC" in a .net Framework 4.6.1 console application

**Comment by djee-ms** [comment]
Hi @smedasn,
Sorry but .NET Framework is not supported, only .NET Standard is supported. So I am closing this bug as invalid. This is most likely because the NuGet package doesn't contain a framework directory for .NET Framework, so the DLL is inside the package but not copied/referenced by NuGet or Visual Studio. You can still work around it I think by manually copying it. But we have no plan to support .NET Framework officially.
