### ISSUE TITLE
Import/Integration in Unity comes with missing namespace errors

### ISSUE THREAD

**Issue by sesd777** [microsoft/MixedReality-WebRTC#168]
Hi, I'm trying to integrate WebRTC for MR into a new Unity project as documented [here](https://microsoft.github.io/MixedReality-WebRTC/manual/helloworld-unity-importwebrtc.html).
After following the steps I end up with a non working project.

Im using the lastest Unity 2018.3.X (2018.3.14f1)

The steps i did in short:
- created new unity project and closed Unity
- cloned this repo (master)
- inside this repo I copied from: libs/Microsoft.MixedReality.WebRTC.Unity/Assets/
the Microsoft.MixedReality.WebRTC.Unity folder,
the Microsoft.MixedReality.WebRTC.Unity.Editor folder
and the Plugins folder
and pasted them in the Assets/ folder of my unity project.
- then downloaded the nuget packages (1.0.2) and copied the native DLLs aswell as the C# Library as explained in the documentation's tables

- opened Unity and found this:
![unity errors](https://user-images.githubusercontent.com/59968860/72539974-7221ab80-3880-11ea-9b17-245e77c5e668.PNG)

I haven't imported any MR toolkit or packages of any kind.

My goal is to build the project and deploy the solution to HoloLens 1 later.

**Comment by djee-ms** [comment]
Yes @sesd777 I believe you did the same mistake as #166, that is you cannot mix the NuGet packages (built from `release/1.0`) with the Unity source code of `master`, which contains API breaking changes and is in essence the code for the future 2.0 release. You either want to copy the 2 folders you copied but taken from the `release/1.0` branch, to get the latest stable version of the project, or you want to recompile `Microsoft.MixedReality.WebRTC.Native.dll` and `Microsoft.MixedReality.WebRTC.dll` from the provided Visual Studio solution using the `master` branch, to get the latest features. But there is currently no NuGet package of MixedReality-WebRTC corresponding to the `master` branch (this is by design).

**Comment by sesd777** [comment]
> Yes @sesd777 I believe you did the same mistake as #166, that is you cannot mix the NuGet packages (built from `release/1.0`) with the Unity source code of `master`, which contains API breaking changes and is in essence the code for the future 2.0 release. You either want to copy the 2 folders you copied but taken from the `release/1.0` branch, to get the latest stable version of the project, or you want to recompile `Microsoft.MixedReality.WebRTC.Native.dll` and `Microsoft.MixedReality.WebRTC.dll` from the provided Visual Studio solution using the `master` branch, to get the latest features. But there is currently no NuGet package of MixedReality-WebRTC corresponding to the `master` branch (this is by design).

yep, that helped. Ty for clarifying

**Comment by djee-ms** [comment]
Sorry that caused confusion. I added a note on the README to clarify.
