### ISSUE TITLE
Audio stream category selection

### ISSUE THREAD

**Issue by shyam-tilt** [microsoft/MixedReality-WebRTC#189]
Hi,

In the Unity implementation is it possible to select the audio stream category as mentioned here
https://docs.microsoft.com/en-us/windows/mixed-reality/voice-input#communication

Is **_AudioCategory_Communications_** the best option in reducing background noise when working in a noisy industrial environment?

**Comment by djee-ms** [comment]
Hi,
No this is not currently possible, at the moment we use the default built-in audio implementation from Google and there is little control over it. Hopefully #99 will open the path to have some better and more customizable audio capture though.

**Comment by fibann** [comment]
From a cursory look at the audio capture code it looks that we are indeed using `AudioCategory_Communications` which seems to be the recommended category for calls. Do we want to add the option _not_ to use it (and if we do, why)?

**Comment by djee-ms** [comment]
Yes because I believe `AudioCategory_Communications` is the one that makes the other sounds reduced/muted, which is a problem for some applications (see #263).

**Comment by fibann** [comment]
No, these are orthogonal:
- this issue (#189) is about selecting the **audio input** stream category. This should affect _on the sending side_ how input audio from the mic is processed before being passed to the app. AFAICS we are using the `AudioCategory_Communications` category that is the recommended one for calls. So nothing to do here unless there are cases where we want to capture and stream something that isn't just voice (for which - I speculate - `AudioCategory_Communications` might not be recommended, and `AudioCategory_Other` would be preferable). Is this the case?
- #263 is about selecting the **audio output** device, specifically selecting the "default device" instead of the "default communication device". This affects _on the receiving side_ whether Windows reduces the volumes of other apps running on the system or not.

**Comment by djee-ms** [comment]
Ah sorry I misread, yes indeed I don't believe we need something else for now. I believe `AudioCategory_Communications` is the best for all applications we had so far, unless someone steps in to say they want support to stream music. But I would argue the focus for Mixed Reality is voice transport.

**Comment by djee-ms** [comment]
@shyam-tilt I'm closing this issue as I think the questions were answered. If not please feel free to reopen. I don't think _a priori_ you would benefit from another audio category, reading the descriptions and from bits of knowledge gathered about this it looks like the best noise reduction for voice content would already be provided by the current category. But feel free to further detail your use case or any issue if there's anything we can help with.
