### ISSUE TITLE
Refactor wrapper handles in interop API

### ISSUE THREAD

**Issue by fibann** [microsoft/MixedReality-WebRTC#207]
Each object in the interop API has two "handles" - a "handle" (simply), that identifies the native (C++) object, and an "interop handle", which, despite the name, usually identifies a wrapper for the native object in the upper layer (e.g. C# binding). The API functions generally use "simple handles", but the upper layer is also supposed to pass the wrapper handle to the API on object creation, and the interop library is supposed to pass it back as a callback argument when needed. The result is that there are a lot of handle types and handle parameters in the API, and both interop lib and wrapper layer have to deal with, and keep around, both. This is very confusing (because of the naming, among other things).

There are several ways this can be addressed, see e.g. https://github.com/microsoft/MixedReality-WebRTC/pull/202#discussion_r385640676. From IRL discussions, it might be worth trying a model where a) interop/wrapper handles are renamed to "user data", and b) user data for an object is not requested on every object creation, but explicitly for the minority (?) of objects that need it.

**Comment by stephenatwork** [comment]
We discussed 3 options:

1. exposing the c++/c# handles as is currently in #202 
2. exposing only the c++ handle and having an associator of c++ & c# handle (e.g. map or weak ptr, etc)
3. exposing only the c++ handles and allowing duplicates of c# objects ("lightweight wrappers")

1&2 keep the 1:1 relationship between c# wrappers and implementation objects at the cost of extra complexity/management.
2&3 can project to more than one language within the same process. 1 appears to have a problem if there are more than one kind of interop handle?
3 allocates additional wrapper objects (increased gc pressure). And also can cause confusion about object identity; wrappers over the same underlying object may compare as different.

**Comment by djee-ms** [comment]
The version proposed by @fibann is the one we discussed further yesterday, and is a variant of 1. where the "handle" terminology refers exclusively to an implementation object, and instead of manipulating explicitly some "wrapper handle" (_e.g._ reference to C# object) the implementation layer associates to the implementation objects some opaque "user data" with some API to set/retrieve those. This has several advantages:
- No more confusion about handles
- "User data" is a well-known concept, carries the meaning of opaque data the implementation DLL will not touch but only pass around where needed, and that the user can use for anything
- In the hypothetical case where a binding does not need wrappers (_e.g._ pure C app?) then it can simply skip setting any user data, so the current "wrapper handle" concept is not mandatory anymore.
