### ISSUE TITLE
How to stream video and return them back? 

### ISSUE THREAD

**Issue by jangyoon107** [microsoft/MixedReality-WebRTC#252]
Hello all, (this is a very helpful project. please keep up the good work! :) )

I am currently trying to get hololens's camera stream and receive images from PC side and do a bit of processing and return the result to hololens for viewing.
I have read the documents and tested the unity project but I was wondering if you could give me the gist of how to use webrtc in such a scenario?

**Comment by djee-ms** [comment]
Hi- I guess you want to add a local video track to send the PV camera, and on the PC side you want to use an [`ExternalVideoTrackSource`](https://microsoft.github.io/MixedReality-WebRTC/api/Microsoft.MixedReality.WebRTC.ExternalVideoTrackSource.html) to send back the custom processed video.

**Comment by jangyoon107** [comment]
I failed to mention that im using the unity integrated version of webrtc. 
I believe that ExternalVideoTrackSource is not accessible from unity integration...

**Comment by djee-ms** [comment]
It is accessible, but you probably want to use a custom component derived from [`CustomVideoSource<T>`](https://microsoft.github.io/MixedReality-WebRTC/api/Microsoft.MixedReality.WebRTC.Unity.CustomVideoSource-1.html) instead for convenience.

**Comment by jangyoon107** [comment]
I think you answered my old question. 
The new question is that customvideosource.cs and scenevideosource.cs in the master branch but not in 1.0.3. version. But the master branch has issue with building unity version library. So, is the custom input not compatible at the moment?

**Comment by djee-ms** [comment]
The external video source feature is only available on `master` indeed.

What's the issue with building the Unity library? I tried recently, this should work. But you need to also build the native plugin and C# assembly from `master`, because the ones from the NuGet packages are built from the `release/1.0` branch and use the old API where the external video source doesn't exist yet. See [Building from sources](https://microsoft.github.io/MixedReality-WebRTC/manual/building.html) for details. Note that there was a change recently and `Microsoft.MixedReality.WebRTC.Native.dll` was renamed to `mrwebrtc.dll`; there is a [pending PR](https://github.com/microsoft/MixedReality-WebRTC/pull/251) to fix some issue left after this rename, maybe that was the issue you hit?
