### ISSUE TITLE
[Unity] Can't get any SDP message on comm Holo1-Desktop

### ISSUE THREAD

**Issue by dhrosquete** [microsoft/MixedReality-WebRTC#290]
**Describe the bug**
Can't get any SDP Message on Unity console and the remote player is not displaying the remote camera

**To Reproduce**
1. Download the **release/1.0** DLLs
2. Putting those in their respective folders
3. Assemblying the scene as indicated on instructions. With a local and remote source
4. Using Unity 2018.4.19
5. Incorporating MRTKv2.3 
6. Running the node-dss server
7. Obtaining the IDs from the node-dss server
8. Build and deploy for Hololens 1 with the remote peer id of the desktop
9. Running from Unity editor with remote peer id of the Hololens
Optional: I'm using the OBS Virtualcam as webcam, but I don't think that is the problem, since I used it without it and have the same issue.

**Expected behavior**
When I run the app I can see the local video on Desktop and in Hololens, the node-dss server is reporting to see both devices. However the Unity console doesn't show any SDP message and the remote player is not displaying the other device camera.

**SDP messages**
I don't have any or maybe I'm not checking in the right place

**Screenshots**
On the left side is the local source, on the right side is the remote source
From Unity running:
![image](https://user-images.githubusercontent.com/15934934/79962329-2fc3c800-8488-11ea-9b20-fc12ae7a6bd9.png)

From node-dss:
![image](https://user-images.githubusercontent.com/15934934/79962411-4a963c80-8488-11ea-9713-6a5e0e1fb2bf.png)

From Hololens: 
![20200422_104418_HoloLens](https://user-images.githubusercontent.com/15934934/79962509-6994ce80-8488-11ea-9691-8af0600847f8.jpg)

**Environment**
 - Platform: UWP (Hololens 1), Unity Editor,]
 - Architecture: [x86, x64]
 - Unity version (if applicable): [2018.4]
 - Target device: [e.g. Windows Desktop, HoloLens 1]

**Additional context**
I've tried changing the Local video source codec to VP8 on Hololens and None, but is no difference.

**Comment by djee-ms** [comment]
First, just to make sure, since you're using the NuGet DLLs, you need to use the Unity scripts from the `release/1.0` branch to have a compatible API. Is that the case? Though that wouldn't explain no SDP anyway, but can cause other issues.

Second, also just to confirm, you don't mention creating an SDP offer. Do you actually have one of the peer calling [`PeerConnection.StartConnection()`](https://microsoft.github.io/MixedReality-WebRTC/api/Microsoft.MixedReality.WebRTC.Unity.PeerConnection.html#Microsoft_MixedReality_WebRTC_Unity_PeerConnection_StartConnection)? This is not done automatically, the call needs to be initiated by one of the peers.

Note that codecs issues make audio/video transfer fail, but do not influence SDP message passing, so you would still see some messages and would still get a connection if the error was just some unsupported codec. Also worth mentioning, if using the Unity Editor, you cannot use H.264, but VP8 is fine (and None currently defaults to VP8).

**Comment by dhrosquete** [comment]
Thank you @djee-ms for your quick response!

Yes, I'm using the Unity scripts of the same branch 1.0

About the StartConnection, I can see is included in master branch but this operation doesn't exist on PeerConnection.cs 1.0. Nevertheless, It has an auto start option, I don't know if that is related to the same process.

Now that you tell me that is a MUST to start the connection, I've done the same procedure described on the VideoChat Example on release 1.0 and it works!

About the codecs, thank you so mucho for your explanation!


Thank you so much! You have done a great job with this development

**Comment by djee-ms** [comment]
Ah right sorry in `release/1.0` it's still called `CreateOffer()` instead of `StartConnection()`, we renamed on `master` to avoid confusion with the method in the C# library.

**Comment by djee-ms** [comment]
Also `AutoStart` means that the peer connection is automatically initialized (the native plugin is loaded, and the native peer connection created and initialized). Admittedly the wording is confusing here.

**Comment by dhrosquete** [comment]
Thank you!!! You have been really helpful and this tool is amazing!

**Comment by djee-ms** [comment]
Thanks for the kind word, and sorry for the trouble; do you think we should add a comment somewhere in the documentation? Where would you expect to see this explained?

**Comment by dhrosquete** [comment]
I will think about how this step could fit properly and let you know tomorrow
