### ISSUE TITLE
Unity crashes in PeerConnection_Create

### ISSUE THREAD

**Issue by motionsmith** [microsoft/MixedReality-WebRTC#293]
Hello! Whenever my application calls `Microsoft.MixedReality.WebRTC.PeerConnection.InitializeAsync()`, Unity crashes.

Here is a stacktrace from the Editor.log:
```
  at <unknown> <0xffffffff>
  at (wrapper managed-to-native) Microsoft.MixedReality.WebRTC.Interop.PeerConnectionInterop.PeerConnection_Create (Microsoft.MixedReality.WebRTC.Interop.PeerConnectionInterop/PeerConnectionConfiguration,intptr,intptr&) [0x0006f] in <d82031f03e4a471c85b553ce27ddc643>:0
  at Microsoft.MixedReality.WebRTC.PeerConnection/<>c__DisplayClass71_0.<InitializeAsync>b__0 () [0x00029] in <d82031f03e4a471c85b553ce27ddc643>:0
  at System.Threading.Tasks.Task.InnerInvoke () [0x00010] in <437ba245d8404784b9fbab9b439ac908>:0
  at System.Threading.Tasks.Task.Execute () [0x00011] in <437ba245d8404784b9fbab9b439ac908>:0
  at System.Threading.Tasks.Task.ExecutionContextCallback (object) [0x00006] in <437ba245d8404784b9fbab9b439ac908>:0
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool) [0x00073] in <437ba245d8404784b9fbab9b439ac908>:0
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool) [0x00004] in <437ba245d8404784b9fbab9b439ac908>:0
  at System.Threading.Tasks.Task.ExecuteWithThreadLocal (System.Threading.Tasks.Task&) [0x00054] in <437ba245d8404784b9fbab9b439ac908>:0
  at System.Threading.Tasks.Task.ExecuteEntry (bool) [0x0005e] in <437ba245d8404784b9fbab9b439ac908>:0
  at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () [0x00002] in <437ba245d8404784b9fbab9b439ac908>:0
  at System.Threading.ThreadPoolWorkQueue.Dispatch () [0x00075] in <437ba245d8404784b9fbab9b439ac908>:0
  at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () [0x00000] in <437ba245d8404784b9fbab9b439ac908>:0
  at (wrapper runtime-invoke) <Module>.runtime_invoke_bool (object,intptr,intptr,intptr) [0x0001f] in <437ba245d8404784b9fbab9b439ac908>:0
```

And here is the thread stack trace from the error.log:
```
Stack Trace of Crashed Thread 25440:
0x00007FFD7B0831FA (Microsoft.MixedReality.WebRTC.N) Microsoft::MixedReality::WebRTC::DataChannel::Send
0x00007FFD7B087729 (Microsoft.MixedReality.WebRTC.N) Microsoft::MixedReality::WebRTC::DataChannel::Send
0x00007FFD7B087359 (Microsoft.MixedReality.WebRTC.N) Microsoft::MixedReality::WebRTC::DataChannel::Send
0x00007FFD7B082B33 (Microsoft.MixedReality.WebRTC.N) Microsoft::MixedReality::WebRTC::DataChannel::Send
0x00007FFD7B07DC10 (Microsoft.MixedReality.WebRTC.N) mrsPeerConnectionCreate
0x000001E5A96CDC10 (Microsoft.MixedReality.WebRTC) Microsoft.MixedReality.WebRTC.Interop.PeerConnectionInterop.PeerConnection_Create()
0x000001E5A96CC5BB (Microsoft.MixedReality.WebRTC) <>c__DisplayClass71_0.<InitializeAsync>b__0()
0x000001E50A7EED41 (mscorlib) System.Threading.Tasks.Task.InnerInvoke()
0x000001E50A7EE3FA (mscorlib) System.Threading.Tasks.Task.Execute()
0x000001E50A7EE23B (mscorlib) System.Threading.Tasks.Task.ExecutionContextCallback()
0x000001E50A7ECA79 (mscorlib) System.Threading.ExecutionContext.RunInternal()
0x000001E50A7EC2FB (mscorlib) System.Threading.ExecutionContext.Run()
0x000001E50A7EA9DB (mscorlib) System.Threading.Tasks.Task.ExecuteWithThreadLocal()
0x000001E50A7E825B (mscorlib) System.Threading.Tasks.Task.ExecuteEntry()
0x000001E50A7E7E63 (mscorlib) System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
0x000001E50A7E2FD1 (mscorlib) System.Threading.ThreadPoolWorkQueue.Dispatch()
0x000001E50A7E1AA3 (mscorlib) System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
0x000001E50A7E1EF5 (mscorlib) <Module>.runtime_invoke_bool()
0x00007FFD7D6DCBA0 (mono-2.0-bdwgc) mono_get_runtime_build_info
0x00007FFD7D662112 (mono-2.0-bdwgc) mono_perfcounters_init
0x00007FFD7D688E41 (mono-2.0-bdwgc) mono_threads_set_shutting_down
0x00007FFD7D68B4C1 (mono-2.0-bdwgc) mono_threads_set_shutting_down
0x00007FFD7D685A78 (mono-2.0-bdwgc) mono_threads_set_shutting_down
0x00007FFD7D685806 (mono-2.0-bdwgc) mono_threads_set_shutting_down
0x00007FFDE7467BD4 (KERNEL32) BaseThreadInitThunk
0x00007FFDE92ACE51 (ntdll) RtlUserThreadStart
```

**Environment**
 - Platform: Unity Editor
-  Player: UWP
 - Unity version 2019.3
 - Target device: HoloLens 2

**Additional context**
I am not using the `...MixedReality.Unity.PeerConnection` class because we are developing a multi-peer solution and also are making our own signaling system. Finally, we are not using Audio/Video, only the data channel. We may like to use audio later, but want to get things working with data only for now.

**Comment by djee-ms** [comment]
```
0x00007FFD7B082B33 (Microsoft.MixedReality.WebRTC.N) Microsoft::MixedReality::WebRTC::DataChannel::Send
0x00007FFD7B07DC10 (Microsoft.MixedReality.WebRTC.N) mrsPeerConnectionCreate
```

That callstack transition is impossible, `mrsPeerConnectionCreate()` never calls `DataChannel::Send()`. This most likely means you use some mismatching API for `mrwebrtc.dll` and the Unity scripts.

See `README.md`:
> Note: The master branch contains the code for the next release, and therefore sometimes contains breaking API changes from the latest stable release. It is therefore not guaranteed to work with NuGet packages, which are only available for stable releases. In particular, the Unity integration scripts are only guaranteed to be compatible with NuGet packages if copied from a release/* branch.

**Comment by motionsmith** [comment]
Thanks for following up quickly.

We re-integrated the library from scratch with v1.0.3, via the webrtc release/1.0 branch (made from [this commit](https://github.com/microsoft/MixedReality-WebRTC/commit/7d47006a819c719250aa47f984052389636eab52) and [these Nuget packages](https://www.nuget.org/packages/Microsoft.MixedReality.WebRTC/1.0.3)). The problem is still happening, and my call stack is the same, it still apparently calls `DataChannel::Send()`.

We do not have a file called `mrwebrtc.dll`. I believe that is a rename of the `WebRTC.Native.dll` to avoid the periods right? Our understanding is that our native libraries should still be called `Microsoft.MixedReality.WebRTC.Native.dll` in v1.0.3.

Thank you for your help. We are committed to getting this working.

**Comment by djee-ms** [comment]
Yes, I edited my answer, this is `Microsoft.MixedReality.WebRTC.Native.dll` in v1.0.3. I _think_ I have seen this erroneous callstack in the past, but can't remember the details.

I've tried the following:
- `git clone --recursive https://github.com/microsoft/MixedReality-WebRTC.git -b release/1.0 mr-webrtc-1.0` (note the `--recursive` is probably useless, I thought about that later)
- Create a new Unity empty project
- Close Unity
- Copy the `Assets` folder of the GitHub clone (except the `Scenes` sub-folder) into the newly created Unity project
- Download NuGet [`Microsoft.MixedReality.WebRTC@1.0.3`](https://www.nuget.org/packages/Microsoft.MixedReality.WebRTC/1.0.3)
- Copy `Microsoft.MixedReality.WebRTC.dll` and `Microsoft.MixedReality.WebRTC.Native.dll` to the new Unity project's `Assets/Plugins/Win32/x86_64/` folder.
- Open Unity and load the project
- Add a new empty GameObject
- Add a `PeerConnection` component and a `NodeDssSignaler` component
- Configure `PeerConnection.Signaler` = `NodeDssSignaler` and set some dummy Local and Remote ID values
- Press Play

The Unity Editor starts playing, the PeerConnection component loads the native DLL and initialize the underlying native peer connection and library, and the Unity console displays the messages:
```
Initializing WebRTC plugin...
Found video capture device '...'
WebRTC plugin initialized successfully.
```
All as expected.

I've also checked the content of the managed DLL with ILSpy, and the content of the native DLL with dumpbin, and everything looks OK. The signature of the `mrsPeerConnectionCreate()` method also matches, and all arguments have the correct size on both sides (native/managed). So I see no reason for that callstack unfortunately.

I've also tried something closer to your use case : deleted the components and added a new GameObject with a custom script containing only this:

```cs
using UnityEngine;
using Microsoft.MixedReality.WebRTC;

public class MyPC : MonoBehaviour
{
    PeerConnection pc = new PeerConnection();

    void Start()
    {
        // bug in 1.0, cannot pass config: null to InitalizeAsync()
        var config = new PeerConnectionConfiguration();
        pc.InitializeAsync(config).ContinueWith(t => Debug.Log("Initialized"));
    }
}
```

Again when pressing Play in the Editor there's no issue and I see the "Initialized" message.

Can you please try the steps above in a new project, so we can understand if the issue is related to something you do in your app, or some configuration that can repro outside your app, and know where to look next?

**Comment by motionsmith** [comment]
Thanks again, your response helped me work through (this part of) it. I'm still getting crashes, but they are different so I can make a new issue if I get too stuck.

I believe the issue was that I was calling PeerConnection methods before initialization was complete. Also, it seems like the native PeerConnection needs to be Initialized from the main thread? Not sure if you have found this to be true for yourself. Anyway, thanks for your help. I might be back for more as I get stuck on other crashes :)

**Comment by djee-ms** [comment]
I don't think there's any requirement to call `InitializeAsync()`. On UWP internally it defers to the UI thread to ask for camera/microphone permission, but that's about it. Did you see some issue with this?
