### ISSUE TITLE
MixedReality-WebRTC/examples/TestNetCoreConsole doesn't build with 1.0.3

### ISSUE THREAD

**Issue by psantosl** [microsoft/MixedReality-WebRTC#297]
Very simple, a project that just imports 1.0.3 can't even build a new program using the examples/TestNetCoreConsole.

I guess it builds with master, but it would be awesome to have some code that builds with the latest official package :)

**Comment by psantosl** [comment]
BTW, I put together a small example to test DataChannel here: https://github.com/psantosl/testMixedReality-WebRTC

**Comment by djee-ms** [comment]
- `examples/TestNetCoreConsole` builds on `release/1.0` with the NuGet 1.0.3 packages. Note that there is a small misconfiguration in the solution, the project pulls some older prerelease package instead of 1.0.3, but I checked locally this makes no difference.
- `examples/TestNetCoreConsole` builds on `master` with the source-compiled native library from that branch.

This all works as expected. `master` contains the latest changes (including API breaking changes) and therefore is not guaranteed to be compatible with the stable 1.0 API, as indicated in the README. There is currently no NuGet package that is compatible with the new upcoming 2.0 API present on `master`, and even if there was as a general rule `master` contains latest changes and needs to be compiled from sources. If you do not want to recompile from sources, and want to use only precompiled NuGet packages, then you should look at the code on `release/1.0`.

**Comment by psantosl** [comment]
Thanks!
