### ISSUE TITLE
Building master branch: some DLLs seem to be skipped

### ISSUE THREAD

**Issue by CabbageWarrior** [microsoft/MixedReality-WebRTC#300]
Hi everyone, and thanks a lot for your work.

**Describe the bug**
Building the "master" branch doesn't generate all the DLLs and AARs, so I have a lot of .meta files unpaired.
Please let me know if there are any problems with this or if I can ignore the unpaired .meta files in order to proceed with the creation of a new Unity project.

**To Reproduce**
1. Clone the meta branch
2. Open the .sln file
3. Build the solution
4. Wait
5. Check the Plugins subfolders
6. Notice the .meta files without files

**Expected behavior**
I expect to see one file per single .meta in my "Plugins" subfolders.

**Output**
<details open><summary>Build Output</summary>
<code>
1>------ Build started: Project: Microsoft.MixedReality.WebRTC, Configuration: Debug Any CPU ------

2>------ Skipped Build: Project: mrwebrtc-win32, Configuration: Debug ARM ------

2>Project not selected to build for this solution configuration

3>------ Skipped Build: Project: mrwebrtc-win32-tests, Configuration: Debug Win32 ------

3>Project not selected to build for this solution configuration 

1>Microsoft.MixedReality.WebRTC -> D:\0_Projects\Mix\MixedReality-WebRTC\bin\netstandard2.0\Debug\Microsoft.MixedReality.WebRTC.dll

4>------ Build started: Project: Microsoft.MixedReality.WebRTC.TestAppUWP, Configuration: Debug ARM ------

5>------ Skipped Build: Project: Microsoft.MixedReality.WebRTC.Tests, Configuration: Debug x64 ------

5>Project not selected to build for this solution configuration

6>------ Skipped Build: Project: TestNetCoreConsole, Configuration: Debug Any CPU ------

6>Project not selected to build for this solution configuration

7>------ Skipped Build: Project: TestReceiveAV, Configuration: Debug Any CPU ------

7>Project not selected to build for this solution configuration

4>  Microsoft.MixedReality.WebRTC.TestAppUWP -> D:\0_Projects\Mix\MixedReality-WebRTC\bin\UWP\ARM\Debug\TestAppUwp.exe

========== Build: 2 succeeded, 0 failed, 1 up-to-date, 5 skipped ==========
</code>
</details>
<details open><summary>.meta files without own file</summary>

- MixedReality-WebRTC\libs\Microsoft.MixedReality.WebRTC.Unity\Assets\Plugins\arm64-v8a\libwebrtc.aar.meta

- MixedReality-WebRTC\libs\Microsoft.MixedReality.WebRTC.Unity\Assets\Plugins\arm64-v8a\mrwebrtc.aar.meta

- MixedReality-WebRTC\libs\Microsoft.MixedReality.WebRTC.Unity\Assets\Plugins\Win32\x86_64\mrwebrtc.dll.meta

- MixedReality-WebRTC\libs\Microsoft.MixedReality.WebRTC.Unity\Assets\Plugins\Win32\x86_64\mrwebrtc.pdb.meta

- MixedReality-WebRTC\libs\Microsoft.MixedReality.WebRTC.Unity\Assets\Plugins\WSA\x86_64\mrwebrtc.dll.meta

- MixedReality-WebRTC\libs\Microsoft.MixedReality.WebRTC.Unity\Assets\Plugins\WSA\x86_64\mrwebrtc.pdb.meta
</details>

**Environment**
 - VS Version: 2019

**Comment by djee-ms** [comment]
First, if you build a single config in Visual Studio, you cannot expect all Windows variants to be populated. You have to build all configs you need.

Second, Android is not built with Visual Studio. You need to build the Google repository following the instructions [here](https://github.com/microsoft/MixedReality-WebRTC/tree/master/tools/build/libwebrtc) to get the `libwebrtc.aar`, then build the `mrwebrtc.aar` with the Android Studio project.

**Comment by djee-ms** [comment]
And yes if you don't care about those configs then you can ignore the unpaired `.meta` files, Unity will delete them.

**Comment by CabbageWarrior** [comment]
Right, thanks a lot for the explanation! I thought that the build command was configured to make all the builds in sequence, except for the Android one. Sorry for the n00b question, and thank you very much for the help! Have a nice day!

**Comment by djee-ms** [comment]
No worry @CabbageWarrior! We're using the default behavior of Visual Studio which is to build only the current config. Ideally we'd have a command-line build script that builds everything for you without even having to open Visual Studio though, but we're working on this and that is not ready yet. Please bear with me ;)

**Comment by CabbageWarrior** [comment]
Absolutely no problem! Rather I apologize if I seemed pressing. You are archmages and I know it takes a long time to prepare the most powerful spells. In the meantime, I do my best on my part to learn how to make your efforts work even for an apprentice like me!

I also use this message to confirm that I am managing to make everything work, after building the libraries individually. Now I am setting up the Unity project for HoloLens 2, and I am spying on the repository in case of implementations for more than two users per "session". Dreaming is beautiful.

Thanks again for your support! :D

**Comment by djee-ms** [comment]
@CabbageWarrior don't hold your breath on multi-peer support, it is not a problem of resources or will to implement, this is simply impossible to implement purely inside this library because WebRTC is a peer-to-peer technology, and the standard will never support > 2 peers.

The way multi-peer (>2) works in practice is that you create a peer-to-peer connection between each participant and a server, and the server has N connections (for N participants) and dispatches the audio and video. There are several well-known technologies for that (see [MCU](https://webrtcglossary.com/mcu/) and [SFU](https://webrtcglossary.com/sfu/) for the most common ones), but they all require a media server. Alternatively you can build a ["mesh"](https://webrtcglossary.com/mesh/) of connections (N-1 connections to every other peer), which is much easier to do but consumes a lot more bandwidth.

If you don't use a mesh topology, currently MixedReality-WebRTC does not ship with any special integration for any of the existing MCU/SFU media servers, but there is nothing stopping you from integrating this project with the server of your choice. I know some other users have tried already; search the issues for references if you want. There are paid and free options out there. Since WebRTC is standardized, there should be no compatibility issue. The main work is to figure out the signaling with the server, because this is not part of the WebRTC 1.0 standard; in general each server will have its own signaling protocol, and you need to write/find an implementation to use with MixedReality-WebRTC to be able to connect to the server.

**Comment by CabbageWarrior** [comment]
I suspected it. In a previous implementation with HL1 during last year I implemented the "mesh of connections" solution manually, but the project was involving a single video sender and the other users were only receivers. We opted for the WebRTC protocol to have as little latency as possible.

I will absolutely study the other two options and I'll check if we can use one of them according to hardware and project specs.

You are saving my day. I must offer you a beer sooner or later!
