### ISSUE TITLE
No offer/answer messages are created

### ISSUE THREAD

**Issue by HyperLethalVector** [microsoft/MixedReality-WebRTC#314]
**Describe the bug**
This is in relation to : https://github.com/microsoft/MixedReality-WebRTC/issues/303#issuecomment-621698775 

I've created two scenarios, one using the basic node-dss (from a fresh build and project import) and the second from my custom signaling service, which was working before I pulled yesterday.

Currently any call to StartConnection(), CreateOffer() or CreateAnswer() doesn't generate any messages, and the OnSDPOfferReadyToSend/OnSdpAnswerReadyToSend aren't being called.

**To Reproduce**
1. Pull & build latest Mr-Webrtc master
2. Open the generated unity project, setup the videoconferencing scene to use the node-dss server that's setup (I added a few debug logs 
3. Hit play
4. No message is generated

**Expected behavior**
Previously on step 4 with the basic node-dss example, a message would be generated.

Using a build from the release branch works well with both the node-dss signaling, and my custom websocket signaling.

**Environment**
 - Platform: Unity Editor
 - Unity version: 2018.4

**Comment by djee-ms** [comment]
I have not tried, but if I follow exactly your steps then I do not expect anything to be generated.

Messages are only generated when a session starts to be negotiated with `StartConnection()`. This doesn't happen automatically at Unity startup unless you are in the very specific (and implementation defined behavior) where : your PeerConnection component is initialized first by Unity, AND the Signaler is initialized next, AND the peer connection finished to connect, AND the various tracks are initialized after that and raise a RenegotiationNeeded event, AND you have `AutoCreateOfferOnRenegotiationNeeded = true`. Any other deviation will fail to automatically generate an offer. And since the order in which Unity starts components is implementation-dependent, there is no expectation that this works. You _can_ force the order of the scripts but I wouldn't rely on that if I were you, this is all too brittle.

Now assuming that you are indeed calling `Startconnection()`, for example via the "CreateOffer" button in the Unity scene, then I followed those steps:
- Start the `node-dss` server after using `set DEBUG=dss*` to see requests
- `git clone --recursive https://github.com/microsoft/MixedReality-WebRTC/`
- Open the Visual Studio solution, build Debug x64
- Open Unity, load the `VideoChatDemo` scene
- Configure the NodeDssSignaler with the correct local/remote peer IDs
- Press Play
- Start TestAppUWP
- Configure the signaler with the correct local/remote peer IDs
- Press the "CreateOffer" button in the `VideoChatDemo` scene

As expected, I do get some offer and answer, and the connection establishes. I can see the 2 video tracks in TestAppUWP.

**Comment by HyperLethalVector** [comment]
After investigating further I found my signaler's implemented update method hid the inherited method, perhaps it's possible to implement the base update method as virtual? 

Either way, the hidden method handled task dequeues, closing the issue.

**Comment by djee-ms** [comment]
@HyperLethalVector I am not sure what base class you are talking about because `Signaler` already has [a virtual `Update()` method](https://github.com/microsoft/MixedReality-WebRTC/blob/050680e4b900f61d1f290b2e98b8fe5b711f3130/libs/Microsoft.MixedReality.WebRTC.Unity/Assets/Microsoft.MixedReality.WebRTC.Unity/Scripts/Signaling/Signaler.cs#L205).

**Comment by HyperLethalVector** [comment]
Strange, it wasn't on my end but after a revert it was. I'll blame me for
it (don't code at 1am folks!). Either way I was hiding the original method,
which was causing the issue I posted.

Thanks anyways for entertaining my silly mistake.
