### ISSUE TITLE
Only Video Stream from Hololens 

### ISSUE THREAD

**Issue by SaschaKll** [microsoft/MixedReality-WebRTC#34]
Hello, i use the VideoChatDemo once on the PC as UWP App and once on the Hololens. So far the transmission works fine.
But I would like to see only the video stream from the Hololens on the UWP app from the PC. I disabled the LocalVideoPlayer in the UWP app on the PC. Unfortunately still needs a webcam or Microphone on the PC. I disconnect it from the PC and start the app I get the following error message:

`Audio/Video access failure: One or more errors occurred.`

Is it possible to run the app without webcam or microphone? Only the video stream from the Hololens should be displayed.

Any suggestions?

Thanks for your help

**Comment by djee-ms** [comment]
Hi @SaschaKll,

I am assuming you are talking about the VideoChatApp sample in Unity? This was not really designed to work with one-way communication. But if you want to try and modify it, my first guess would be to look at the [`StreamingCaptureMode`](https://docs.microsoft.com/en-us/uwp/api/windows.media.capture.streamingcapturemode), which is by default set to both audio and video:

https://github.com/microsoft/MixedReality-WebRTC/blob/b72fe6cb7199ae32035e18ccf4a3a2fca5a4b06c/libs/Microsoft.MixedReality.WebRTC.Unity/Assets/Microsoft.MixedReality.WebRTC.Unity/Scripts/PeerConnection.cs#L396-L401

This is I believe the reason why you are getting that exception. Note that in your case if you don't want any audio nor video streaming out of the PC, you can entirely skip the call to `MediaCapture.InitializeAsync()`, which is only there to request A/V access from the user on UWP, and directly call `PeerConnection.InitializePluginAsync()`.

After that you also probably need to disable the `LocalVideoPlayer` on the PC side as you did. There might be other things to do, I never tried that scenario.

**Comment by SaschaKll** [comment]
Thanks for the quick answer. Yes I mean the example project in Unity.

I will test the one you suggested.

Thank you

**Comment by djee-ms** [comment]
The Unity app should probably be more clever and not assume A/V is needed until it's actually requested, and only request if there is a Unity component for local audio and/or video.

**Comment by nous-** [comment]
@djee-ms I can confirm your changes for one-way communication work. Thanks for the info. We have an existing project using [HoloLensCameraStream](https://github.com/VulcanTechnologies/HoloLensCameraStream), and bringing in MixedReality-WebRTC started producing silent conflicts, due to competing use for local streams.

**Comment by djee-ms** [comment]
@nous- ok good to hear that works. Incidentally, can I ask why you are using HoloLensCameraStream? I am not familiar with that project but I read its description quickly (so I may have oversimplified or misunderstood) and it seems that all that project does is provide access to the raw HoloLens video frames, is that correct? Because in that case you already have access to those via the [`PeerConnection.I420LocalVideoFrameReady`](https://microsoft.github.io/MixedReality-WebRTC/api/Microsoft.MixedReality.WebRTC.PeerConnection.html#Microsoft_MixedReality_WebRTC_PeerConnection_I420LocalVideoFrameReady) event (or the remote event if you want to access them on the other peer).

**Comment by nous-** [comment]
We use this HoloLensCameraStream to get per frame transformation information for [Locatable Camera](https://docs.microsoft.com/en-us/windows/mixed-reality/locatable-camera) operations.

As an aside, we bind a UDP port via `Datasocket`. The moment the WebRTC streams start, no further messages arrive on the bound port. Anything you might know about this?

**Comment by djee-ms** [comment]
@nous- Not sure what you mean, nor what `Datasocket` is referring to. I take that it's not a WebRTC thing. I don't have a clue why a UDP port would be blocked, aside from being otherwise used by WebRTC already.

**Comment by djee-ms** [comment]
This was fixed some time ago, `PeerConnection` now only request audio access on UWP because we have no choice (Google's audio module tries to access the microphone at startup, and will crash if not available). Otherwise the permissions have been moved as expected to:
- `MicrophoneSource.OnEnable()` for microphone permission request
- `WebcamSource.OnEnable()` for camera permission request

This ensures that permissions are only requested when actually needed, and will allow no-video scenarios to proceed without video permission (but not audio, due to the aforementioned Google limitation).

**Comment by astaikos316** [comment]
@nous- I was wondering how you were able to run both HoloLensCameraStream and WebRTC on the Hololens and not have a crash.  It appears when I try and capture a photo while webrtc is attached to the camera, it crashes the app.
