### ISSUE TITLE
How to fix the problem of remote video offset on PC?

### ISSUE THREAD

**Issue by suxinren** [microsoft/MixedReality-WebRTC#355]
Hi @djee-ms 

On the PC, the video shown in the "RemoteVideoPlayer", that is, the video captured by the HoloLens, is not centered and shifted to the left. l want to achieve the brush synchronization function, draw some handwriting on the PC, display on the HoloLens.And then you can see the composite video on the PC, but the handwriting on both sides can not overlap. Whether I try to modify the size of the texture or modify the size of the GameObject, even through synchronize the resolution of both sides  can not achieve the purpose, how can I do the handwriting overlap on both sides or how to ensure that remote video is centered.

 It's easier to express if the editor supports uploading images.

**Comment by djee-ms** [comment]
Hi @suxinren,

- The video shifted is probably because the size of the video sent from the remote peer changed, but the local textures that it is uploaded to are still the old size. You should check in the frame callback the size of the frame, and check the size of the texture(s) in the MediaPlayer component. There might be a bug where we don't update them correctly.
- "Brush synchronization" (sometimes called "inking" or "ink strokes" also I think) can be done 2 ways:
  - For "2D" style, you locally embed the inking into the video before it is sent to the remote peer. This is not very easy currently because you cannot intercept the frames from the local video and modify them.
  - For "3D" style, you can send the inking path and color for example through a data channel, and re-render it on top of the video on the remote peer. This is generally preferred since you can have 3D inking path that doesn't depend on the camera position.

The GitHub text editor supports uploading images; just drag and drop the image inside the text area and it will upload.

**Comment by suxinren** [comment]
Hi @djee-ms 
Inking function I have achieved, now the problem is that the two sides of the handwriting can not overlap, my goal is to make the two sides of the handwriting overlap. The video that HoloLens sent back is not centered, and the relevant settings can not be found on the RemoteVideoPlayer GameObject.
According to your suggestion, I looked at the video resolution, the resolution at both sides is the same, but the video returned from the HoloLens is smaller than the local video.

![896x504](https://user-images.githubusercontent.com/24662429/82277325-24e25180-99ba-11ea-9e4e-333933a5d3a2.png)
![1280x720](https://user-images.githubusercontent.com/24662429/82277343-2ad83280-99ba-11ea-9ec8-d1a62613dcb2.png)
![Inking](https://user-images.githubusercontent.com/24662429/82277353-30ce1380-99ba-11ea-94e9-608ab3c89131.png)
![Untitled](https://user-images.githubusercontent.com/24662429/82277359-362b5e00-99ba-11ea-961d-46d4d7c55be5.png)
![VideoResolution](https://user-images.githubusercontent.com/24662429/82277369-3e839900-99ba-11ea-9ea0-991f49655ce5.png)

**Comment by djee-ms** [comment]
> the relevant settings can not be found on the RemoteVideoPlayer

There is no setting on the remote side by design. This is how WebRTC works, how the WebRTC 1.0 standard is defined. Only the sender decides the resolution it sends, the receiver cannot control anything. I don't like it either, but we can't do anything about it, it's in the standard so it's as expected.

> the video returned from the HoloLens is smaller than the local video.

I am not sure I understand. Are you saying that the local video on the PC has a different size from the video that HoloLens is sending? You can configure that. If you want the same resolution then configure the capture on both peers to be the same. Each peer captures video from a webcam, you just need to force the resolution to be the same (and choose one that both PC and HoloLens support).

I am confused because the first screenshots shows "896 x 504" which is typically an HoloLens resolution (never seen that on PC), but then your last screenshot shows the Unity editor, so I assume that this is the remote video coming from HoloLens, and now it's 720p (1280 x 720), which is different. That makes no sense to me; the resolution that WebRTC sends is the resolution that the webcam capture, we don't do any resizing, and especially not upscaling.

I don't know what's your second screenshot; looks exactly the same as the first but indicates some different resolution. Also your camera is not normalized in the 3rd screenshot; it's "Holo (1268 x 720)" for some reason, which is a weird ratio, and not a resolution supported by HoloLens (see [here](https://docs.microsoft.com/en-us/windows/mixed-reality/locatable-camera)).

**Comment by suxinren** [comment]
Hi @djee-ms 
First of all, I'm sorry, I didn't describe my problem clearly.
<blockquote>
<p>Are you saying that the local video on the PC has a different size from the video that HoloLens is sending? </p>
</blockquote>
 Yeah, that's what I mean.

**Comment by lust0yixiong** [comment]
> According to your suggestion, I looked at the video resolution, the resolution at both sides is the same, but the video returned from the HoloLens is smaller than the local video.

Hi，I am also trying solve the Ink problem between PC and Hololens. There is a problem i have met: How can i converter the screen position in pc to world position in Hololens? I have tried Camera.ScreenToWorldPoint(Vector3 position), but the result are always zero.
Could you give me some help? 
Thanks very much!

**Comment by suxinren** [comment]
Hi @lust0yixiong 
I didn't make any changes,I'm just sending PC position to the HoloLens.
The main code is as follows:
<pre>
//PC  code
//Initialize the canvas code
texture = new Texture2D(canvaTextureWidth, canvaTextureHeight);
canva.transform.localScale = new Vector3(canvaWidth, canvaHeight, 1);
canva.GetComponent<MeshRenderer>().material.mainTexture = texture;    

Update()
{
	...
    else if (Input.GetMouseButton(0))//按住
    {
        var ray = Camera.main.ScreenPointToRay(Input.mousePosition);
        RaycastHit hit;
        if (Physics.Raycast(ray, out hit))
        {
            if (hit.collider.name == "Canva")
            {
                Vector2 pixelUV = hit.textureCoord;
                pixelUV.x *= texture.width;
                pixelUV.y *= texture.height;
                mousePos = new Vector2(pixelUV.x, pixelUV.y);

                //Draw handwriting from current position and previous position
                Draw(mousePos);
                string msg = mousePos + "|" + previousPosition;
                peerConnection.SendMsg((int)MsgType.Data, msg);
            }
            //Debug.Log("Pos:"+mousePos);
        }
    }
    ...
}

//Hololens code
private void PeerConnection_OnMsgReceived(byte[] arrMsg)
{
	...
    try
    {
        if (msgType == (int)MsgType.Data)
        {
            Array.Copy(arrMsg, 2, arrData, 0, arrMsg.Length - 2);
            string msg = System.Text.Encoding.UTF8.GetString(arrData);

            if (msg.Contains("|"))//position|prePosition  (,,)|(,,)
            {
                string[] arrBrushInfo = msg.Split('|');
                if (arrBrushInfo.Length == 2)
                {
                    DrawReceive(StrToVector2(arrBrushInfo[0]), StrToVector2(arrBrushInfo[1]));
                }
            }
            else
            {
                texture.Apply();
            }
        }
        ...
    }
    catch (Exception ex)
    {
        strMsg = ex.Message;
    }
}

</pre>
PC and HoloLens need to set the same canvas size and texture size.
The Canva GameObject must have MeshCollider component.

**Comment by lust0yixiong** [comment]
> PC and HoloLens need to set the same canvas size and texture size.
> The Canva GameObject must have MeshCollider component.

I am not sure I understand. As you mentioned, the Ink operation just refers to the Canvas, that means it only effective in virtual environment, can't related to reality environment, am I right?

**Comment by suxinren** [comment]
Hi @lust0yixiong 
The Ink operation is available both in PC and HoloLens. Plot on the PC, then synchronize the coordinates to HoloLens,HoloLens accepted coordinate message and perform the drawing operation so that both sides can display handwriting.

**Comment by lust0yixiong** [comment]
> Hi @lust0yixiong
> The Ink operation is available both in PC and HoloLens. Plot on the PC, then synchronize the coordinates to HoloLens,HoloLens accepted coordinate message and perform the drawing operation so that both sides can display handwriting.

I understand your solution。
I also find another issue：the video direction of Hololens in PC is opposite with the true vision, did you met the same problem?

**Comment by suxinren** [comment]
@lust0yixiong
> I also find another issue：the video direction of Hololens in PC is opposite with the true vision, did you met the same problem?

![HorizontalMirror](https://user-images.githubusercontent.com/24662429/83130870-8e2c3800-a111-11ea-86c9-41186d4d0be9.png)

**Comment by lust0yixiong** [comment]
> @lust0yixiong
> 
> > I also find another issue：the video direction of Hololens in PC is opposite with the true vision, did you met the same problem?
> 
> Enable the "Horizontal Mirror" option.
> 
> ![HorizontalMirror](https://user-images.githubusercontent.com/24662429/83130870-8e2c3800-a111-11ea-86c9-41186d4d0be9.png)

Thank you very much！！It is helpful

**Comment by lust0yixiong** [comment]
> @lust0yixiong
> 
> > I also find another issue：the video direction of Hololens in PC is opposite with the true vision, did you met the same problem?
> 
> Enable the "Horizontal Mirror" option.
> 
> ![HorizontalMirror](https://user-images.githubusercontent.com/24662429/83130870-8e2c3800-a111-11ea-86c9-41186d4d0be9.png)

About your question，i have an idea but maybe not right(have not test yet): the FOV of Hololens is 43 and the default unity is 60, maybe the difference caused the offset.

**Comment by suxinren** [comment]
>  @lust0yixiong
> About your question，i have an idea but maybe not right(have not test yet): the FOV of Hololens is 43 and the default unity is 60, maybe the difference caused the offset.

FOV I've thought about it, but it's not a FOV problem, so far I've solved the problem, I' ve tried to modify the width and height of the Canva and the Texture, and then I've tried many times, and I' ve found that the offset is regular, and then I've constantly modified the offset value to make the PC and Hololens handwriting completely coincide.

**Comment by lust0yixiong** [comment]
> I tried to modify the video resolution and the texture resolution make sure PC and Hololens have the same configuration

I have noticed that the "Holo" resolution set as 1268*720 but not 1280*720, i am not sure it is right

**Comment by suxinren** [comment]
> I have noticed that the "Holo" resolution set as 1268x720 but not 1280x720, i am not sure it is right

The resolution of the hardware has nothing to do with the resolution of the texture or canva, for example, although the resolution of the HoloLens is 1268*720, I can still set the canva or texture resolution to 1920*1080. 
Are you Chinese?

**Comment by lust0yixiong** [comment]
> Are you Chinese?

Yes，you too?
These days i tried to fix the problem the same with you met. I think maybe it is the calibration issue between physic camera and the mixedreality camera. I am not sure if i am right, still trying...

**Comment by suxinren** [comment]
> Yes，you too?
恩，加个QQ或者微信吧，我可以手把手教你咋解决。
我的QQ：304923993   QQ群：376663834    160145295 ，微信：suxinrenzs
