### ISSUE TITLE
No Frames after VideoTrackRegistered?

### ISSUE THREAD

**Issue by rygo6** [microsoft/MixedReality-WebRTC#402]
This isn't so much a bug, just hoping to get some help on an issue I am stuck with.

I have an Unity project that was forked off of MRWebRTC months ago, and it is working. However it had some issues that had been fixed upstream. Also I figure it would be best to keep my fork in sync with the latest in case some of the stuff I am working on should merge back. So I have pulled in all the latest upstream changes, I have seemingly gotten everything refactored to work with the new changes in MRWebRTC as far as I can tell, but it doesn't work.

The issue specially is that after a `Transceiver` is attached to a `VideoReceiver`, and after a `RemoteVideoTrack` is paired to the same `VideoReciever`, it never starts to receive frames. The frame callback never gets called.

It appears to me everything that should occur before it starts receiving frames is correct. The `TransceiverAdded` callback is fired off of `PeerConnection`. The `VideoTrackAdded` callback is then fired off of `PeerConnection`. But then the `I420AVideoFrameReady` callback never gets called on the `RemoteVideoTrack`, neither does `Argb32VideoFrameReady`.

The oddity about this is I can run the project still running on the old MRWebRTC codebase and connecting to the same backend, it loads right up and starts receiving frames.

Is there some new additional step I am missing since the frame calbacks were moved off `PeerConnection` and onto `RemoteVideoTrack`?

**Comment by rygo6** [comment]
I ended up sorting this out. For anyone that runs into this, the answer from my peer was not registering back correctly through my signaler. VideoTracks register, but frames don't start until the proper answer is returned.

**Comment by djee-ms** [comment]
Hi @rygo6,

Glad this is fixed. Anything we could have done to help you better diagnose? It seems that if the answer was never received by the caller then there's not much we can do but wait for it, so unfortunately there's no opportunity to log an error anywhere, no?

The way it works _in my limited understanding_ is that the callee received the offer so invoked the track added callback. It then sends back an answer and immediately starts sending back frames too, as a warmup to avoid delays (this is allowed by WebRTC). However on the caller even if those frames are received they are likely discarded until the answer that negotiates them is actually received and applied. Because frames and answer go through different network paths (frames are peer-to-peer via (S)RTP, answer is through signaling) the frames can arrive earlier, and/or any of those can get blocked while the other is not.

**Comment by rygo6** [comment]
Thanks for the in depth explanation that makes things clearer. 

I don't know if there would be anything more to do.  Perhaps a log that says the answer is sent, but still no response? That could at least signify the issue didn't exist in mrwebrtc. But I don't know, as really I just needed to read more into webrtc to understand it better.
