### ISSUE TITLE
Cannot run latest master built from source code 

### ISSUE THREAD

**Issue by astaikos316** [microsoft/MixedReality-WebRTC#437]
**Describe 
I have been trying to build the latest master from source for the last few days in order to do some android work. When I finally try to open the unity video sample scene, I get a stream of errors about PeerConnectionEditor null reference to a sprite image. When I look at the peer connection gameobject, the transceiver portion does not fully show up. 

**To Reproduce**
1. Built android portion on Linux machine
2. Transferred over to windows machine 
3. Built visual studio solution for x64/x86/arm
4. Copy unity folder to new unity project then load video sample
5. See PeerConnectionEditor sprite bull reference errors when peerconnection gameobject is selected.
6. PeerConnection GameObject is missing portions of it (no place to specify transceivers)

**Environment**

 - Platform: Unity Editor
 - Architecture:  Unity Editor is x64 on Windows
 - Unity version (if applicable): 2019.3.0f1
 - Target device: [Android Phone]

**Comment by djee-ms** [comment]
> 4. Copy unity folder to new unity project then load video sample

This is why. The setup has changed, the `libs/unity/library` folder now has the organization of a Unity Package Manager (UPM) package. The recommended way is to drop your binaries into `libs/unity/library/Runtime/Plugins/` and then using the UPM window to import that package from disk into your folder. See [Local solution build](https://microsoft.github.io/MixedReality-WebRTC/manual/unity/helloworld-unity-importwebrtc.html#local-solution-build) in the docs for details.

The reason it doesn't work by copying is because the icon image for the `PeerConnectionEditor` is referenced by its path from the package (some path starting with `Packages/com.microsoft.mixedreality.webrtc/`). I _think_ just changing that path would make things work for you, but that's not really how we intend users to consume that library anymore, as the UPM package way is much easier. And soon we will even have UPM packages with precompiled binaries.

**Comment by cy238** [comment]
> The reason it doesn't work by copying is because the icon image for the PeerConnectionEditor is referenced by its path from the package (some path starting with Packages/com.microsoft.mixedreality.webrtc/). I think just changing that path would make things work for you.

Yes, this does indeed work. `PeerConnectionEditor` is the only thing causing issues if you don't use the UPM way. So adjusting/commenting out the sprite loading part is enough to make it work.

**Comment by astaikos316** [comment]
I corrected that original issue.  Now when I tried to build to android i get a list of errors all saying "missing Type or namespace" for multiple parts, about 96 errors in total.  I made sure the libwebrtc.aar file is in the project but I have not had success.

**Comment by djee-ms** [comment]
@astaikos316 something's outdated, please check again, I built Android 5 min ago and it worked. Recompile the C# library on Windows, that's probably it.

**Comment by astaikos316** [comment]
I have been doing that since yesterday.  I will try again.  Do I just rebuild the solution file?

**Comment by astaikos316** [comment]
I rebuilt the solution file for all 3 architectures on windows and still getting the Android build errors in Unity stating missing Type or Namespace" for all components

**Comment by djee-ms** [comment]
Then Unity is likely ignoring the DLL on Android. What's the import settings on the `Microsoft.MixedReality.WebRTC.dll`?

**Comment by astaikos316** [comment]
Its set to Editor and Standalone and Platform Settings has Any CPU and Any OS

**Comment by djee-ms** [comment]
And not `Any Platform`? Then it's used in the Editor and deployed in Standalone (PC) builds, and not on Android, so that's why it doesn't work.

**Comment by astaikos316** [comment]
Now that I have changed that, I can get it to build and run but when i try to run a session between PC and tablet, the moment I hit Create Offer in the sample, i stop seeing tablet messages in the nodedss console window and i never see the PC video stream on the tablet side.  I am at a loss because i thought it could have been a video codec issue like I have run into in the past but i do not see where that is configured anymore.  Then I tried disabling the local video/audio on the tablet side before building out the app and still have the same issue.

**Comment by astaikos316** [comment]
@djee-ms Wanted to add another update here.  I was able to pull up console logs on the tablet and when running the build I get the following error:

AndroidJavaException: UnsatisfiedLinkError: No implementation found for void org.webrtc.PeerConnectionFactory.nativeInitializeAndroidGlobals()

Tablet is running Android 9.

**Comment by djee-ms** [comment]
> I also had to remove the libwebrtc.aar from the project structure or it wouldn't build.

Yes this is by design.

> Also, to run in editor I have to switch platforms from Android to PC each time. If i try to run in editor set to android build I get the following exception:

This is by design of the Unity Editor unfortunately. I can't do anything about it.

> AndroidJavaException: UnsatisfiedLinkError: No implementation found for void org.webrtc.PeerConnectionFactory.nativeInitializeAndroidGlobals()

Did you just delete `libwebrtc.aar`? It seems you have stale and inconsistent changes between the old experimental preview where we used both `libwebrtc.aar` and `mrwebrtc.aar`, and the newer approach where we merge everything into `mrwebrtc.aar`. My guess is that you have an old build of `mrwebrtc.aar` which doesn't contain the merged `libwebrtc.aar`.

**Comment by astaikos316** [comment]
I tried a fresh build of mrwebrtc.aar this morning after pulling the repository again this morning.  Everything appears to build fine.  I am not given any indication in Android Studio that there is a problem or anything.

**Comment by djee-ms** [comment]
Ok and you still have the issue? Because I spent all week working on Android for adding video capture and I had no issue like this.

**Comment by astaikos316** [comment]
Yes the issue is still there.

**Comment by djee-ms** [comment]
Are you exporting the Android Studio project from Unity and building / deploying from Android Studio itself?
Because that function is definitely present, so I have no idea why it would not find it, this is the first time I see this.

![image](https://user-images.githubusercontent.com/49064175/86486964-c64c1980-bd54-11ea-91af-a5581f583fe2.png)

Is your tablet supporting ARM64? Because on Android that's the only architecture we support. But I expect there would be other errors than that and you wouldn't even be able to deploy, but just checking in case...

**Comment by astaikos316** [comment]
I haven’t been doing that at all. I build the libraries on my Linux machine. Then move the repo over to my windows machine. Build visual studio solution. Then open Unity, set build to Android and it gives me the apk I install on the tablet.

**Comment by astaikos316** [comment]
@djee-ms   Figured out that the build was running with Mono instead of IL2CPP. got rid of those previous errors but I now cannot get a Local camera feed on the tablet. App permissions do not reference camera or mic and when I try to make a call to the pc tablet gives error of value cannot be null for medialines

**Comment by djee-ms** [comment]
Unity fails to detect the RECORD_AUDIO and WEBCAM permissions because they're accessed internally (C++) instead of via Unity scripts (C#) so those permissions should be added manually in your `AndroidManifest.xml`. RECORD_AUDIO is always needed, WEBCAM is only needed if you use video.

**Comment by astaikos316** [comment]
@djee-ms i did manage to figure that out over the weekend that that was happening. The last thing I am having trouble with is figuring out is how the camera device is assigned because I’m trying to use the rear camera on the Samsung tablet but I haven’t been able to figure out how to assign the rear camera’s device. I can pull the device ID and I can confirm which ID is not front facing.

**Comment by djee-ms** [comment]
I can't remember the details but I think Google's implementation possibly forces the front camera. Please open a separate issue if you need that to be configurable.

**Comment by astaikos316** [comment]
Thank you @djee-ms.  Closing this issue and going to open a new one for the Configurable Camera.
