### ISSUE TITLE
Unity crashes when AutoInitializeOnStart is true in PeerConnection 

### ISSUE THREAD

**Issue by SimGu96** [microsoft/MixedReality-WebRTC#442]
Hi, 
I have a problem similarly to this: https://github.com/microsoft/MixedReality-WebRTC/issues/218
Where Unity crashes when starting play mode when AutoInitializeOnStart is true in PeerConnection.
I have tried both making a new scene and following the tutorial (https://microsoft.github.io/MixedReality-WebRTC/versions/release/1.0/manual/helloworld-unity.html) and trying the sample VideoChatDemo, with the same result.

I have no microphone or webcam plugged in except the webcam in my laptop.

I installed as specified in: https://microsoft.github.io/MixedReality-WebRTC/versions/release/1.0/manual/installation.html

I'm running:
Unity 2019.3.15f1
MixedReality-WebRTC-release-1.0
microsoft.mixedreality.webrtc.1.0.3
microsoft.mixedreality.webrtc.uwp.1.0.3

**Comment by djee-ms** [comment]
Can you please share more info about the crash @SimGu96? There can be any number of reason why the code crash on startup; unsupported audio device is a common one due to #242 but not the only one. Do you see an exception in Unity before the crash? Do you get a crash dump? Can you connect the Visual Studio debugger and try to see in the Output window what is going on before the crash? Normally you should see some error message, the code rarely crashes without any.

**Comment by SimGu96** [comment]
Unity basicly shuts down with no warning or crach dump. When connecting to the Visual Studio debugger, the only output after all the "Loaded: Module: ... " lines is: 
The program 'Unity' has exited with code 0 (0x0).

I'm running Windows 10 on my MacBook pro with Boot Camp, but i don't see why that would be a problem.

Thanks

**Comment by SimGu96** [comment]
I tried to run it on the HoloLens 2 and it seems to work great there. So you are probably right with it being an unsupported audio device.

Will have to test on the HoloLens from now on.

Thanks
