### ISSUE TITLE
how to use DataChannel class to send datas between PC and Hololens

### ISSUE THREAD

**Issue by zhuisa** [microsoft/MixedReality-WebRTC#445]
how to use DataChannel class to send datas between PC and Hololens? Need establish a peerconnection on both sides? Are there some examples? I need to send and receive some files between PC and Hololens .

**Comment by djee-ms** [comment]
See the `TestAppUWP` sample for an example of use:
- Create a new data channel with [`PeerConnection.AddDataChannelAsync()`](https://microsoft.github.io/MixedReality-WebRTC/api/Microsoft.MixedReality.WebRTC.PeerConnection.html#Microsoft_MixedReality_WebRTC_PeerConnection_AddDataChannelAsync_System_String_System_Boolean_System_Boolean_CancellationToken_) or wait for the remote peer to create one by subscribing to the [`PeerConnection.DataChannelAdded`](https://microsoft.github.io/MixedReality-WebRTC/api/Microsoft.MixedReality.WebRTC.PeerConnection.html#Microsoft_MixedReality_WebRTC_PeerConnection_DataChannelAdded) event like [here](https://github.com/microsoft/MixedReality-WebRTC/blob/d70cc5ee9f1ed99ff545949f3c21b962bb7e02dd/examples/TestAppUwp/Model/SessionModel.cs#L345).
- Send data with [`DataChannel.SendMessage()`](https://microsoft.github.io/MixedReality-WebRTC/api/Microsoft.MixedReality.WebRTC.DataChannel.html#Microsoft_MixedReality_WebRTC_DataChannel_SendMessage_System_Byte___) like [here](https://github.com/microsoft/MixedReality-WebRTC/blob/ff0e558d745dd4faaa50c3bc5b96b6112d278a1f/examples/TestAppUwp/ChatChannelsPage.xaml.cs#L53).
- Receive data by subscribing to the [`DataChannel.MessageReceived`](https://microsoft.github.io/MixedReality-WebRTC/api/Microsoft.MixedReality.WebRTC.DataChannel.html#Microsoft_MixedReality_WebRTC_DataChannel_MessageReceived) event like [here](https://github.com/microsoft/MixedReality-WebRTC/blob/d70cc5ee9f1ed99ff545949f3c21b962bb7e02dd/examples/TestAppUwp/Model/ChatChannelModel.cs#L63-L67).

There is no Unity component because the data channel API is very slim and only transport bytes, so there's not much to configure in Unity. Instead you can directly access that API from the C# library via [the `Peer` property](https://microsoft.github.io/MixedReality-WebRTC/api/Microsoft.MixedReality.WebRTC.Unity.PeerConnection.html#Microsoft_MixedReality_WebRTC_Unity_PeerConnection_Peer) of the [`PeerConnection`](https://microsoft.github.io/MixedReality-WebRTC/api/Microsoft.MixedReality.WebRTC.Unity.PeerConnection.html) Unity component, which exposes the underlying C# library object.

Note: all links are for the `master` branch.

**Comment by zhuisa** [comment]
thanks for your guidance, i solved it .

**Comment by djee-ms** [comment]
Alright, closing then, cheers!

**Comment by zxzkf1992** [comment]
> thanks for your guidance, i solved it .

Hello, I also want to implement a simple data transfer function between the PC and HoloLens, such as json files or txt files.
Could you please share with me how you solved it?
