### ISSUE TITLE
Build by unity,in hololens2 the local media never render,but when I test in unityeditor they works.

### ISSUE THREAD

**Issue by Jason-Chn95** [microsoft/MixedReality-WebRTC#502]
My build settings was open the webcam,microphone and internet,but in hololens2 the local video didnot render,I use the DevicePortal,the MixedReality Capture Live Preview works,but also cound not show the local video.My npm service works normal,so who can tell me why?Thx.

**Comment by djee-ms** [comment]
We need more information than that to diagnose what's happening.

- Are you using Unity or the C# library (or the C/C++ library)?
- What version/branch/commit of the code are you using?
- Are you using the VideoChatDemo or some other custom scene setup? Where did you expect the local video to render?
- Does the app works on another device, like a PC? Is the problem specific to HoloLens 2?
- You say "the MixedReality Capture Live Preview works,but also cound not show the local video", what does that mean? Is the MRC preview working in the device portable and showing some video or not? Also you should avoid using MRC from the device portal at the same time as your application, I don't think using MRC from 2 different apps at the same time works well or at all.
- "My npm service" : I assume you are using `node-dss` for signaling? But you are talking about the local video, which doesn't require a WebRTC connection since it's local, so signaling should be irrelevant.

It would have been easier to use the Bug Report template.
