### ISSUE TITLE
Stuck Sending Video using C API

### ISSUE THREAD

**Issue by mcfly3001** [microsoft/MixedReality-WebRTC#503]
Hi,

I could successfully get the library running with the Unity samples on desktop and even with Android. Next step for me is to use the native C library as a streaming server and connect to Client which is build within Unity.
Unfortunately I am quite stuck as I cannot receive the video stream. Somehow I have the feeling that there is something wrong with the ICE candidates. 
The streaming works with the Unity Demos and the ICE candidates for sender and receiver both propose "network-id 1" when checking the signaler. When using the C API though, my sender never proposes "network-id 1" but other ids like 3, 4, 5, 6.

Maybe also there is something wrong with the created answer in the SDP protocol? Here are some relevant snippets. It would be nice if anyone could give any hints.
[NodeDSS_Snippet.txt](https://github.com/microsoft/MixedReality-WebRTC/files/5028995/NodeDSS_Snippet.txt)
[Cpp_Log.txt](https://github.com/microsoft/MixedReality-WebRTC/files/5028996/Cpp_Log.txt)

**Comment by mcfly3001** [comment]
Just did some more debugging and it seems that the transceiver is inactive by default. Probably I will only have to figure out how to enable the sending.

**Comment by djee-ms** [comment]
Use `mrsTransceiverSetDirection()`, or specify at construction with `mrsTransceiverAddedInfo::desired_direction`.

**Comment by mcfly3001** [comment]
> 
> 
> Use `mrsTransceiverSetDirection()`, or specify at construction with `mrsTransceiverAddedInfo::desired_direction`.

Thanks, that's what I am already doing. It seems that the transceiver changes its direction state. Probably when the offer is coming in. I will try to check the `mrsTransceiverStateUpdatedCallback()` callback to find out more...

**Comment by djee-ms** [comment]
The transceiver created manually on the sender side should not change direction; its direction will be used to craft the offer.

The transceiver created automatically on the receiver side when a remote offer is applied (or answer, but that's more rare) is created as receive-only; that's a Google implementation detail. If I remember correctly you can change the direction before crafting the reply, and that reply will contain the desired direction. Otherwise if you wait for the negotiation to be completed then you need to change the direction after that and re-negotiate.

**Comment by djee-ms** [comment]
The devil's in the detail; I think from what I remember to avoid a renegotiation you need to:
1. Create an offer and send it as "receive only".
2. On the remote, apply the offer.
3. Change the direction of the created transceiver from "inactive" (because offer is "receive only", which means "send only" on the remote (inverted) and default is "receive only", so the intersection of those is "inactive") to "send only", and generally add a track to the transceiver at the same time to actually have something to send.
4. Create the answer with the new transceiver state.

The trick is 3., which happens between the callback registered with `mrsPeerConnectionRegisterTransceiverAddedCallback()` (which is invoked internally during `mrsPeerConnectionSetRemoteDescriptionAsync()`) and the call to `mrsPeerConnectionCreateAnswer()`, which will inspect the state of the transceivers to create the SDP answer. So `mrsTransceiverSetDirection()` needs to override the default direction either in the transceiver added callback, or just before calling `mrsPeerConnectionCreateAnswer()` after receiving and applying the offer.
