### ISSUE TITLE
Remove ISignaler as a required input for a new PeerConnection

### ISSUE THREAD

**Issue by eirikhollis** [microsoft/MixedReality-WebRTC#52]
Suggestion.

When creating a new WebRtc.PeerConnection, an ISignaler derived class is required. But looking at the code, the requirement is redundant. Most events are fired as stand-alone events, and if these events are correctly subscribed to in a generic signaler class, the class provided to PeerConnection isn't needed.

In fact, changing lines 429-433:
```
429        public PeerConnection(ISignaler signaler)
430        {
431            Signaler = signaler;
432            Signaler.OnMessage += Signaler_OnMessage;
433        }
```
to the following code
```
public PeerConnection(ISignaler signaler)
{
    if (signaler != null)
    {
        Signaler = signaler;
        Signaler.OnMessage += Signaler_OnMessage;
    }
}
```
would allow for a null signaler to be inserted and still work, since the rest of the ISignaler method calls in PeerConnection check for a null ISignaler, e.g.
```
1215        Signaler?.SendMessageAsync(msg);
```

**Comment by djee-ms** [comment]
First, the fact that there are some null pointer tests is probably redundant because without signaling you cannot establish a peer connection, so this is a mandatory service to have.

Beyond that, I am not sure I follow how that would work. For the events, the signaler implementation could register a handler, yes. But how can the peer connection send messages? Are you suggesting to replace `ISignaler.SendMessageAsync()` with a `PeerConnection.OnMessageReadyToSend` event?

Conceptually though I personally find it better to encapsulate all signaling-related properties and events inside a single interface rather than being mixed with other properties and events inside the `PeerConnection` object, no? But I am eager to educate myself and change opinion if I am missing something here. What is the issue with implementing a small interface like `ISignaler`, and what is the comparative benefit of having standalone events?

**Comment by eirikhollis** [comment]
In my case I subscribe to the peer events (ice, sdp, etc) like this:
```
PeerConnection.IceCandidateReadytoSend += PeerConnection_IceCandidateReadytoSend;
PeerConnection.LocalSdpReadytoSend += PeerConnection_LocalSdpReadytoSend;
PeerConnection.TrackAdded += PeerConnection_TrackAdded;
PeerConnection.TrackRemoved += PeerConnection_TrackRemoved;
```
and the code for e.g. the event _IceCandidateReadytoSend_ in PeerConnection.cs looks like this:
```
private void OnIceCandidateReadytoSend(string candidate, int sdpMlineindex, string sdpMid)
{
    var msg = new SignalerMessage()
    {
		MessageType = SignalerMessage.WireMessageType.Ice,
		Data = $"{candidate}|{sdpMlineindex}|{sdpMid}",
		IceDataSeparator = "|",
		TargetId = RemotePeerId
    };
	
    Signaler?.SendMessageAsync(msg);

    IceCandidateReadytoSend?.Invoke(candidate, sdpMlineindex, sdpMid);
}
```
In my case, since I listen to the _IceCandidateReadytoSend_ event, I don't need the
`Signaler?.SendMessageAsync(msg)`
or even the messageformat of SignalerMessage. In fact, had I used the SendMessageAsync method as well, I would've ended up with duplicates of all ice candidates.
All information about the Ice Candidate is delivered in the event, and I'm able to send this further to the correct recipient.

The same goes for the event _OnLocalSdpReadytoSend_.

**Comment by djee-ms** [comment]
Actually removed `ISignaler` and it seems easier to use now, so I guess that was a good call. See 6ccf6847b0f9e902c18754456bd68acc838181c1 for the change.
