### ISSUE TITLE
How to open sample scene?

### ISSUE THREAD

**Issue by gtk2k** [microsoft/MixedReality-WebRTC#526]
**Describe the bug**
_A clear and concise description of what the bug is._

**To Reproduce**
1. import sample package (download tgz or manifest.json).
2. double click sample scene.
3. Read-only dialog show can't open scene.
![readonly](https://user-images.githubusercontent.com/309829/89729572-01d3b500-da72-11ea-8db9-a6d4146914aa.png)

**Comment by sananbintahir** [comment]
Just copy the scene from packages to your assets

**Comment by djee-ms** [comment]
Never seen that and can't repro; I am guessing you probably have some read-only file Unity wants to write to. In any case this looks like a Unity issue or misconfiguration of your project. You shouldn't have any need to copy anything to your Assets/ folder, you can perfectly open a scene from any package and run it. Unless there has been a recent change in the latest Unity version I didn't try.

**Comment by gtk2k** [comment]
Thanks!
I can open scene.

**Comment by sananbintahir** [comment]
> Never seen that and can't repro; I am guessing you probably have some read-only file Unity wants to write to. In any case this looks like a Unity issue or misconfiguration of your project. You shouldn't have any need to copy anything to your Assets/ folder, you can perfectly open a scene from any package and run it. Unless there has been a recent change in the latest Unity version I didn't try.

Non-embedded unity packages are read-only, and don't support scenes. As far as I know, this was never possible, even in previous unity versions. You won't be able to run the scene unless the package is physically present in the Packages folder in the unity project. Since the installation of the project requires a dependency in the manifest.json file, it is not an embedded package. You either have to embed the package to play the scene or move the scene into the assets folder.

**Comment by djee-ms** [comment]
You are saying that if I download the package and import it from disk from the Unity Package Manager window then I cannot open the scene nor play it? Because I have been doing that just fine with both 2018.4 and 2019.4, either with packages imported from disk or packages downloaded from our custom NPM register. I can also play any scene from the samples package and build+deploy to device. And I have never seen any read-only error like the one above. Again, unless this changed in 2020.x for example, which I never tested.

The only annoyance is Unity 2018.4 silently refusing to open scenes from packages. The workaround is to "Open As Additive" and close the other scene after. This has been fixed in Unity 2019.x at some point though, and is really just a bug.

**Comment by sananbintahir** [comment]
If you install the package from the package manager (adding dependencies in the Packages/manifest.json), the package will not be an "embedded package", meaning it won't be present in your project folder physically, have a look at https://docs.unity3d.com/Manual/upm-embed.html

**Comment by djee-ms** [comment]
Instead it will be present in the Packages/ subfolder of the Asset Browser window, from which you can open any asset.

![image](https://user-images.githubusercontent.com/49064175/89777293-4fe4c900-db03-11ea-8a7b-060f7f598205.png)

**Comment by gtk2k** [comment]
Thanks a lot!

**Comment by sananbintahir** [comment]
To make it clear, when your project folder looks like, 
![Capture1](https://user-images.githubusercontent.com/33203924/89778518-f5049f00-db0d-11ea-99df-2c2631b29ba5.PNG)

You will get the following because the project right now is in Library/PackageCache
![Capture](https://user-images.githubusercontent.com/33203924/89778537-02218e00-db0e-11ea-99f4-39f6491325b9.PNG)

But If you have the package in your packages folder (have to do this manually, adding dependencies in manifest.json will put the package in cache)
![Capture3](https://user-images.githubusercontent.com/33203924/89778655-3301c300-db0e-11ea-8a10-b6f4060669e7.PNG)

Then the scene will open as expected, 
![Capture2](https://user-images.githubusercontent.com/33203924/89778702-4319a280-db0e-11ea-9e81-27532a6b9b87.PNG)

When the package is in the PackageCache folder, you can access all of the assets, but the scenes will not open.
Alternatively, as I mentioned earlier, you could just move the scene into your assets folder.

**Comment by djee-ms** [comment]
I don't know why you have this error nor restriction, this works perfectly fine in both 2018.4 LTS and 2019.4 LTS without the package being copied in your Packages/ folder.

![image](https://user-images.githubusercontent.com/49064175/89782757-c5ee2d80-db0d-11ea-9538-f34896fdc162.png)

Also the project is in Library/PackageCache/ only if imported via the UPM registry. Otherwise it's wherever you put it when you downloaded it on disk. In either case I can open and play any scene without issue. Might be a bug of one specific version of Unity.

**Comment by sananbintahir** [comment]
Interesting. Might be a Unity bug then, like you said.

**Comment by raggnic** [comment]
I have the same isue if i import the package as a tarball. However if it extract the tgz and import the package.json in UPM I can open the samples scenes.
