### ISSUE TITLE
Accessing local audio source frames

### ISSUE THREAD

**Issue by sananbintahir** [microsoft/MixedReality-WebRTC#581]
I want to pre-process the audio frames produced by the microphone locally before they are sent over the peer connection, preferably in Unity. Is it possible to get these frames in the current implementation of the library? If not, any help regarding how I can go about implementing this would be appreciated.

**Comment by djee-ms** [comment]
This is not currently available. The audio stack has 2 potential entry points:
- generic audio post-processing stack
- per-track audio callbacks

The former is not exposed, and the latter was never implemented by Google, so the callbacks won't be called.

If you want to try it yourself, the [`webrtc::AudioProcessing` interface](https://github.com/webrtc-uwp/webrtc/blob/8b8d9f9b768d700684ca73ac183c5474afaf7bc4/modules/audio_processing/include/audio_processing.h#L159-L233) can be implemented and passed as the last argument to [`webrtc::CreatePeerConnectionFactory()`](https://github.com/microsoft/MixedReality-WebRTC/blob/480981ac74a6040b3058d620c0de2fa617d1f301/libs/mrwebrtc/src/interop/global_factory.cpp#L327). However that won't work on UWP because webrtc-uwp-sdk expose internally a different API; luckily I think they also expose some other audio processing wrapper interface. So yeah, it's possible probably but that would require some work. And it is unlikely we will ever expose anything to C# or Unity, as audio processing is generally performance-critical and I suspect too slow if done in C# anyway.

**Comment by sananbintahir** [comment]
Thank you for the detailed answer. I'll try to implement this. UWP isn't an issue since we're not targeting that. You might be correct about audio processing being too slow in C#, but there are implementations that carry out audio processing in Unity. We were using one of these previously and it wasn't very performance-intensive, nor did it seem slow, so it still might be worth a try for us.

**Comment by sananbintahir** [comment]
@djee-ms I had a follow-up question. You said I needed to 'implement' the [`webrtc::AudioProcessing` interface](https://github.com/webrtc-uwp/webrtc/blob/8b8d9f9b768d700684ca73ac183c5474afaf7bc4/modules/audio_processing/include/audio_processing.h#L159-L233), however, I noticed there is already an implementation of it under "modules/audio_processing/audio_processing_impl.h". 

To use this, in [global_factory.cpp](https://github.com/microsoft/MixedReality-WebRTC/blob/master/libs/mrwebrtc/src/interop/global_factory.cpp), I did
```
#include "modules/audio_processing/audio_processing_impl.h"

webrtc::AudioProcessing* apm = webrtc::AudioProcessingBuilder().Create();

if (apm == nullptr) {
  throw 20;
}

apm->echo_cancellation()->Enable(true);
apm->noise_suppression()->Enable(true);
apm->set_stream_delay_ms(0);
```
and then, passed `apm` as the last argument to [`webrtc::CreatePeerConnectionFactory()`](https://github.com/microsoft/MixedReality-WebRTC/blob/480981ac74a6040b3058d620c0de2fa617d1f301/libs/mrwebrtc/src/interop/global_factory.cpp#L327), (I set the stream delay to 0 expecting echo cancellation to cancel out all of the audio, tried without it too)
```
  peer_factory_ = webrtc::CreatePeerConnectionFactory(
      network_thread_.get(), worker_thread_.get(), signaling_thread_.get(),
      nullptr, webrtc::CreateBuiltinAudioEncoderFactory(),
      webrtc::CreateBuiltinAudioDecoderFactory(),
      std::unique_ptr<webrtc::VideoEncoderFactory>(
          new webrtc::MultiplexEncoderFactory(
              absl::make_unique<webrtc::InternalEncoderFactory>())),
      std::unique_ptr<webrtc::VideoDecoderFactory>(
          new webrtc::MultiplexDecoderFactory(
              absl::make_unique<webrtc::InternalDecoderFactory>())),
      custom_audio_mixer_, apm);
```
However, this produced no effect whatsoever on the call.
