### ISSUE TITLE
Managed MRWebRTC dll imports as native dll on mac.

### ISSUE THREAD

**Issue by rygo6-MS** [microsoft/MixedReality-WebRTC#584]
So we are working on a Mac port of this. I've encountered one issue that is fairly puzzling. 

The managed `Microsoft.MixedReality.WebRTC.dll` does not register as a managed dll in Unity on Mac. Same exact project, same exact file, open it in Unity on Windows, it registers as a managed dll as it should. Open it in the editor on Mac, it thinks it is a native dll, and doesn't seem to actually load, giving a bunch of linking errors to the managed methods in that dll.

I've tried to find as much info as I could on why this is happening, but I have not found a good answer. One person mentioned a managed dll having a dependency on a native dll might do this, but the only dependency I see in VS Is .NET standard library. Is there anything that comes to mind about the code in the managed dll that could maybe cause this?

**Comment by djee-ms** [comment]
Hi @rygo6-MS,

Officially we don't support Mac platforms, and I have never used Unity on Mac. If the DLL is not recognized as a managed assembly then that sounds like a Unity bug and I don't think there's much we can do, as the assembly is a .NET Standard 2.0 one so should be multiplatform by design. I'd suggest logging a ticket with the Unity support team; I reckon you probably have a Pro license so should be entitles to some support for it. If you find there's something we can do to help Unity recognize the assembly as such, we'd be happy to consider a patch.

**Comment by rygo6-MS** [comment]
We figured this out. Seemed to make a working dll after doing full clean of latest master and rebuilding the dll. Don't fully understand why.

**Comment by andydbc** [comment]
Hi @rygo6-MS,

Could you elaborate on the steps to build for Unity on macOS ?
