### ISSUE TITLE
Is it possible to create two track, one with MRC, the other without it ?

### ISSUE THREAD

**Issue by hansenwuwu** [microsoft/MixedReality-WebRTC#603]
Is it possible to create two track from the same camera?
I found the code snippet where the source created.
Can I create a source with MRC, and another source without MRC?
```
try
{
    var source = await DeviceVideoTrackSource.CreateAsync(deviceConfig);
    AttachSource(source);

    // is it possible to do something like this?
    var sourceWithoutMRC = await DeviceVideoTrackSource.CreateAsync(deviceConfigWithoutMRC);                
    AttachSource(sourceWithoutMRC);
}
catch (Exception ex)
{
    Debug.LogError($"Failed to create device track source for {nameof(WebcamSource)} component '{name}'.");
    Debug.LogException(ex, this);
    return;
}
```

**Comment by djee-ms** [comment]
I'm not sure. My guess is that it won't work because the webcam cannot be shared by the 2 tracks. It is not a limitation about MRC, but about creating two tracks from the same video capture device. Also that might be quite heavy to process for HoloLens, as this might go over budget for the internal hardware encoder, so might need to fallback to software, which will drain the battery. In short, even if that works, I would discourage it. I would instead switch (destroy/recreate) between a track with and a track without, as needed. Creating a track shouldn't take more than a second or two.

**Comment by hansenwuwu** [comment]
Thank you for the advice!
I will try this idea!

And another question
When I look into the source code
in the "device_video_track_source.cpp" script
I found this line of code to create the video source (I think) (at line 197)
```
auto vcd = wrapper::impl::org::webRtc::VideoCapturer::create(createParams);
```
But I can't find where this function was defined, could you give me some hint.
Thank you so much !!!

**Comment by djee-ms** [comment]
That's for UWP only, this is the UWP wrapper from https://github.com/webrtc-uwp/webrtc-uwp-sdk, it's defined in https://github.com/webrtc-uwp/webrtc-apis/blob/c7ebe56a122d635d7188a1f5d09ad3a77c3accf8/windows/wrapper/impl_webrtc_VideoCapturer.cpp#L1188.

**Comment by hansenwuwu** [comment]
Thank you so much!
This is exactly what i am looking for!
I will go on and dig into it.
