### ISSUE TITLE
WebRTC plugin initializing failed. See full log for exception details

### ISSUE THREAD

**Issue by qazqaz12378** [microsoft/MixedReality-WebRTC#61]
I Build the PC to run
error 
WebRTC plugin initializing failed. See full log for exception details
![image](https://user-images.githubusercontent.com/4353931/64314716-8efcc700-cfe2-11e9-8714-b15e18004446.png)

**Comment by octaviancatlabuga** [comment]
Thanks for the issue, I had the same problem and Load on Startup solved it.

**Comment by maxhutinet** [comment]
@qazqaz12378 i'm facing a similar issue. What do means exactly by "choose Plugin load settings Load on startup" ?

**Comment by octaviancatlabuga** [comment]
@maxhutinet , check this out https://docs.unity3d.com/Manual/PluginInspector.html

**Comment by djee-ms** [comment]
> I found the reason and need to choose Plugin load settings Load on startup

No, that is not the reason, that is at best an arguable workaround, sorry I failed to see this earlier.

The "Load on startup" option of Unity is undocumented (see link from @octaviancatlabuga, there's no mention of it on that page except in the screenshot) but is most likely for forcing a native DLL loading at engine startup even if not needed, instead of waiting for it to actually be needed. So it is only for changing the _timing_ of the loading, not whether it is loaded or not. And C# will automatically load that DLL on first use, so there's no benefit to this. This is only useful when code relies on a DLL without explicitly loading it, which is never the case here.

There are many reasons the MixedReality-WebRTC plugin could have failed its initializing, and if setting this option worked around the issue then it's bad news because it looks like something else was wrong and this undocumented option _as a side-effect_ made the error go away. Don't use that; instead make sure the native DLL (either `Microsoft.MixedReality.WebRTC.Native.dll` or `mrwebrtc.dll` depending on the version) is correctly deployed by Unity, and if not report a bug and we can investigate why this fails. But do not rely on "Load on startup", which has unknown consequences and should not make any difference in theory. My guess is that the DLL was not previously deployed (due to a bug or misconfiguration), so the C# library failed to find it, and with that option Unity deployed it correctly just because to load it at startup it had to first make sure it's deployed, and that side-effect solved the issue, and not the actual loading timing that this option is supposedly controlling.

**Comment by maximehutinet** [comment]
@djee-ms thanks for your response. For some reason i don't have the "Load on startup". I've followed the instruction of the[ Unity integration](https://microsoft.github.io/MixedReality-WebRTC/manual/installation.html).

- I cloned the [repo](https://github.com/microsoft/MixedReality-WebRTC.git) 
- Checked out to the release/1.0 branch
- Copied the content from `MixedReality-WebRTC\libs\Microsoft.MixedReality.WebRTC.Unity\Assets ` to the Asset folder of my Unity project
- Downloaded the two Nuggets packages : [Microsoft.MixedReality.WebRTC](https://www.nuget.org/packages/Microsoft.MixedReality.WebRTC) and [Microsoft.MixedReality.WebRTC.UWP](https://www.nuget.org/packages/Microsoft.MixedReality.WebRTC.UWP)
- Copied all the Microsoft.MixedReality.WebRTC.Native.dll and renamed them mrwebrtc.dll
- Modified the CPU/plateform for each plugin

After unchecking the "Auto Initialize On Start" checkbox of the PeerConnection component the `WebRTC plugin initializing failed` error seems to disapear. However, i assume it's not the right way to solve this issue, is it ?

I am running my project with Unity 2018.4.15

I had few questions :

1.  Do you recommend to use the content from the release/1.0 branch ? I have noticed that few elements that are present in the [Unity tutorial](https://microsoft.github.io/MixedReality-WebRTC/manual/helloworld-unity-localvideo.html) are not present in this branch. For instance the Webcam source script and the transceivers list in the Peer Connection script. I checked the content of the master branch but the folder structure is not the same as the tutorial. The Unity scripts are under `libs\unity\library\Runtime\Scripts` and not `libs\Microsoft.MixedReality.WebRTC.Unity\Assets\Microsoft.MixedReality.WebRTC.Unity\Scripts`

2.  I am a bit confused about wether or not the dll need to be renamed to mrwebrtc.dll or not. Do you have more info about that ? 

Here is the current structure of my project Plugin folder

```
D:.
│   Win32.meta
│   WSA.meta
│
├───Win32
│   │   x86.meta
│   │   x86_64.meta
│   │
│   ├───x86
│   │       mrwebrtc.dll
│   │       mrwebrtc.dll.meta
│   │
│   └───x86_64
│           Microsoft.MixedReality.WebRTC.dll
│           Microsoft.MixedReality.WebRTC.dll.meta
│           mrwebrtc.dll
│           mrwebrtc.dll.meta
│
└───WSA
    │   ARM.meta
    │   x86.meta
    │   x86_64.meta
    │
    ├───ARM
    │       mrwebrtc.dll
    │       mrwebrtc.dll.meta
    │
    ├───x86
    │       mrwebrtc.dll
    │       mrwebrtc.dll.meta
    │
    └───x86_64
            mrwebrtc.dll
            mrwebrtc.dll.meta
```

Thank you so much for your help.

Maxime

**Comment by djee-ms** [comment]
Hi Maxime,

> After unchecking the "Auto Initialize On Start" checkbox of the PeerConnection component the WebRTC plugin initializing failed error seems to disapear. However, i assume it's not the right way to solve this issue, is it ?

Disabling initialization of the library is indeed not the right way to solve anything. You're basically left with some unusable piece of C# code with no access to WebRTC. Unless you're manually calling `PeerConnection.InitializeAsync()`, which I assume will make the error re-appear, because again I strongly suspect it's not about load timing (now vs. later), it's about whether the library is deployed correctly and found. "Auto Initialize On Start" means "automatically call `PeerConnection.InitializeAsync()` during Start()" as opposed to "I will call it myself when I want/need to", but they're both doing exactly the same thing.

> I have noticed that few elements that are present in the Unity tutorial are not present in this branch.

You are looking at the tutorial for `master` while using the code/API for `release/1.0`. Either change the docs version (top right corner of the page) or change your code to use `master`. The `release/1.0` is more simple and easy to use (NuGet) but has missing features. `master` has much more features but no NuGet (yet; we're working toward 2.0).

> I am a bit confused about whether or not the dll need to be renamed to mrwebrtc.dll. Do you have more info about that ?

Same issue as above, you are looking at the wrong documentation:
- `release/1.0` => `Microsoft.MixedReality.WebRTC.Native.dll`
- `master` => `mrwebrtc.dll`

The reason they have different names is they're different things conceptually; the 1.0 DLL was supposed to be also a C++ library, although this is partly broken. In `master` we reverted that and `mrwebrtc.dll` is an implementation module offering a pure C API (not C++). It can still be used from C++, but doesn't expose any C++ type/constructs so is free from any compiler/inlining/template issues usually associated with C++ and DLL.

Again, the docs for each branch describe the branch version and should be in perfect sync (unless there's a bug), and same for the tutorials. I appreciate it's a common issue; if you have some insight on how we can make this more clear please feel free to suggest some change.

**Comment by djee-ms** [comment]
@maximehutinet 2.0.0 is out with UPM packages containing prebuilt binaries, I recommend using that instead of trying to build from sources. See the [Unity tutorial](https://microsoft.github.io/MixedReality-WebRTC/manual/unity/helloworld-unity-importwebrtc.html) to import the packages directly from the new UPM register.
