### ISSUE TITLE
how to render some 3D object on WebCam image?

### ISSUE THREAD

**Issue by kiokju** [microsoft/MixedReality-WebRTC#618]
how to render some 3D object on WebCam image on hololens2?

WebCam Source component render all 3D object on scene inclide 'UI object'.

Scene Video Source component render only 3D object NOT WebCam image on hololens 2.

In any solution to render only some 3D object on WebCam Image ?

**Comment by fibann** [comment]
I suppose you can edit SceneVideoSource so that it
- subscribes to a WebcamSource to get the current video frame
- on Update, renders the current video frame before rendering the 3D scene
- only renders a subset of the objects by e.g. disabling all others using layers or similar (I am not familiar enough with Unity rendering to give you a solution here, sorry).
