### ISSUE TITLE
No Video Stream On Hololens

### ISSUE THREAD

**Issue by Boo0317** [microsoft/MixedReality-WebRTC#62]
It worked well between two Unity Editor,but when i run it on hololens , I can not receive remote video & audio from Hololens on Unity Editor, and the Hololens has no remote video too.It took me a whole day but it has not progressed。
Is there something missing on Hololens? And whether IceServer is necessary?

**Comment by djee-ms** [comment]
Hi @Boo0317,

The setup for HoloLens is the same as for the Unity Editor or any other platform.  If you have no audio nor video on both sides, I'd say that the connection is probably not established correctly.

You have to make sure that the `node-dss` peer IDs are setup correctly, which for HoloLens if you are using the Unity means setting the RemotePeerId property of the NodeDssSignaler component to the value of the local Unity Editor peer before you build and deploy to HoloLens, then changing it back to the peer ID of the HoloLens before pressing Play, as [explained in the tutorial](https://microsoft.github.io/MixedReality-WebRTC/manual/helloworld-unity-connection.html). Also make sure the HTTP address of the `node-dss` server is the IP of the machine hosting it, and not `127.0.0.1`, otherwise the HoloLens won't be able to access it.

If you paste some `node-dss` logs we might have some more clues looking at the messages. You can enable logging by setting the environment variable `set DEBUG=dss*` before running `npm start`.

**Comment by djee-ms** [comment]
To answer your other question, the ICE server(s) are not mandatory. If none is provided, connections will be limited to localhost. See also #20.

**Comment by Boo0317** [comment]
Hi, here is the node-dss logs,

Hololens peer ID : "234"
Unity Editor ID :  "123"
Hololens IP :  192.167.0.117
Unity Editor IP : 192.168.0.118

node-dss server IP: 192.168.0.118
[node-dss-logs.txt](https://github.com/microsoft/MixedReality-WebRTC/files/3582039/node-dss-logs.txt)

**Comment by djee-ms** [comment]
@Boo0317 your answer message (`MessageType=2`) is empty:
```
dss:body {"MessageType":2,"Data":"","IceDataSeparator":"|"} +96ms
```
I don't think there is a problem in the underlying Google implementation, so there is most likely a problem when sending that message. The best way to diagnose is to check for `MessageType=2` in the `LocalSdpReadyToSend` callback, which is fired after calling `CreateAnswer()`, and confirm whether `Data` is empty or not, and why.

If you are using the Unity integration, `CreateAnswer()` is called from `CO_GetAndProcessFromServer()`:
https://github.com/microsoft/MixedReality-WebRTC/blob/fb4a230ab39cf943f581b8caa4592d0f8029401a/libs/Microsoft.MixedReality.WebRTC.Unity/Assets/Microsoft.MixedReality.WebRTC.Unity/Scripts/Signaling/NodeDssSignaler.cs#L210-L214

Then the `LocalSdpReadyToSend` event is handled in the underlying `PeerConnection` object which dispatches to the `Signaler` implementation:
https://github.com/microsoft/MixedReality-WebRTC/blob/fb4a230ab39cf943f581b8caa4592d0f8029401a/libs/Microsoft.MixedReality.WebRTC/PeerConnection.cs#L1336-L1342

If you are using the default `NodeDssSignaler` for Unity, then the SDP answer message should eventually make its way to `PostToServer()`:
https://github.com/microsoft/MixedReality-WebRTC/blob/fb4a230ab39cf943f581b8caa4592d0f8029401a/libs/Microsoft.MixedReality.WebRTC.Unity/Assets/Microsoft.MixedReality.WebRTC.Unity/Scripts/Signaling/NodeDssSignaler.cs#L160-L172

Somewhere along the way the data is lost. I am not sure why. I think putting breakpoints along the way should allow you to diagnose this.

**Comment by Boo0317** [comment]
Thank you for your help,I solved this problem .It seems that Hololens and Unity Editor on the different LAN.
Now I have another problem ，the remote load FPS is too low，only adout 5 FPS.
 I tried setting resolution and frame rate like this [Issue](https://github.com/microsoft/MixedReality-WebRTC/issues/46), but it doesn't work.
What should I do to setting resolution and frame rate or improve remote video fluency?

**Comment by djee-ms** [comment]
This is unfortunately not supported yet. This is tracked by #46 which is still open. I hope to get those changes in next week or so.

I am closing this issue, as the title refers to missing video stream and this is solved. We can continue the discussion on #46 if you believe that the low FPS is related to resolution.
