### ISSUE TITLE
How can I choose a specific webcam?

### ISSUE THREAD

**Issue by Octav1an** [microsoft/MixedReality-WebRTC#64]
Hi,
As far as I understood, for the local video source the first available webcam is chosen. Is it possible to choose a specific one, either by name or id on the Unity side? or get all available webcam devices similar to WebCamTexture.devices in Unity.
Thanks.

**Comment by djee-ms** [comment]
Hi @Octav1an,

Camera selection is available through the unique device ID passed to [`AddLocalVideoTrackAsync()`](https://microsoft.github.io/MixedReality-WebRTC/api/Microsoft.MixedReality.WebRTC.PeerConnection.html#Microsoft_MixedReality_WebRTC_PeerConnection_AddLocalVideoTrackAsync_Microsoft_MixedReality_WebRTC_PeerConnection_VideoCaptureDevice_System_Boolean_), after retrieving a list from [`GetVideoCaptureDevicesAsync()`](https://microsoft.github.io/MixedReality-WebRTC/api/Microsoft.MixedReality.WebRTC.PeerConnection.html#Microsoft_MixedReality_WebRTC_PeerConnection_GetVideoCaptureDevicesAsync). There is no UI on Unity components because this is device-specific, so displaying a list in the Unity Editor would only work on the current PC, and not when deploying on another device. So this needs to be selected at runtime. Or you can build a UI inside your Unity app using those two methods.

See also #46.

**Comment by octaviancatlabuga** [comment]
This is what I was looking for, thanks

**Comment by Octav1an** [comment]
This is what I was looking for, thanks.
