### ISSUE TITLE
API versioning

### ISSUE THREAD

**Issue by aboba** [microsoft/MixedReality-WebRTC#66]
The [RTCPeerConnection API](https://rawgit.com/w3c/webrtc-pc/master/webrtc.html) utilizes `RTCConfiguration` in the `RTCPeerConnection` constructor. 

In practice, `RTCConfiguration` [has been extended to enable API versioning](https://webrtc.org/web-apis/chrome/unified-plan/), so as to enable the transition from the "Plan B" SDP dialect to "Unified Plan". 

How does versioning work in the Mixed Reality SDK?  Does the MR SDK use "Plan B" or "Unified Plan" by default?  Is it possible to specify a non-default API? 

Note that the "Plan B" API dialect has been deprecated and could be slated for removal from Chrome and Edge as soon as 2020.

**Comment by djee-ms** [comment]
Hi @aboba,

This is an excellent question, I was thinking yesterday of documenting that part, so good timing. Currently MixedReality-WebRTC is based off the m71 milestone of Google's webrtc code. In this version Plan B is still the default, and there is currently no parameter exposed to switch to the Unified Plan, simply because there was no demand so far so I didn't have a look at whether it is feasible nor how.

For completeness, there is some on-going work in the background to upgrade MixedReality-WebRTC to the m75 milestone, which has the Unified Plan active by default since m72. But that one might take some time, as I have other priorities [for the next 2 milestones](https://github.com/microsoft/MixedReality-WebRTC/milestones) based on feedbacks from partners.

In the meantime, if you feel the need to have that configuration exposed then we can have a look at how to do that. I am assume that this is just a matter of changing the [`RTCConfiguration::sdp_semantics`](https://github.com/webrtc-uwp/webrtc/blob/baa89682df1ab891ae274a1cb2d9be3b1ee7e20b/api/peerconnectioninterface.h#L558) field, but that would need some testing. If you have some experience doing that and can confirm, I will try to find some time to squeeze some testing and try to expose that parameters, that seems easy enough if there is nothing else to do.

**Comment by djee-ms** [comment]
The default semantic is now the Unified Plan. Added an option to fall back on Plan B if needed, for compatibility. See 87e15921ab91d16f3e56a888353df11e8faba397.
