### ISSUE TITLE
Send encoded frames

### ISSUE THREAD

**Issue by martingra** [microsoft/MixedReality-WebRTC#668]
I have a WPF application that, using EmguCV, performs real time computer vision.

The idea is to send the processed frames to a browser using WebRTC.

I have tow questions at this point:

1) Can I create a video stream from Bitmaps in memory?
2) Can I encode those frames in H.264 before sending them to the browser using this library?

**Comment by djee-ms** [comment]
1. See [`ExternalVideoTrackSource`](https://microsoft.github.io/MixedReality-WebRTC/api/Microsoft.MixedReality.WebRTC.ExternalVideoTrackSource.html)
2. Yes, video frames are encoded by default. Just select H.264 as the codec. Note that H.264 is only implemented for UWP, not for Windows Desktop nor Unity Android. Otherwise you can fallback to another codec like VP8 which works with everything.
