### ISSUE TITLE
VideoChatDemo Example not working

### ISSUE THREAD

**Issue by eanders-MS** [microsoft/MixedReality-WebRTC#72]
Platform: Windows 10
Unity: 2018.3.14f1
Commit: de1db21

When I run the VideoChatDemo scene in Unity, LocalVideoSource correctly shows the webcam feed, and in the console I see ICE signals being received, but no video shows up on RemoteVideoSource. I added a `Connected` handler, but it is never called. Can you suggest a next step in debugging this failure?

**Comment by djee-ms** [comment]
Hi @eanders-MS,

What are the two clients? Are they both the Unity sample scene VideoChatDemo? And if so, is one of them in the Editor, or are they both running standalone in the Unity player? I assume by "Windows 10" you mean Windows Desktop? Or is it UWP?

The `Connected` handler is related to the peer connection being established, and more precisely the internal state machine switching to the `kStable` state after receiving an answer. The remote video will never work before that, so I would focus on that one first. It seems in your case the connection is not established correctly, most likely due to SDP errors (messages not dispatched). There are various causes depending on the actual implementation. If you use node-dss, these include wrong peer IDs, devices on different subnet, firewall rules blocking the connection one way. First step is, if you use node-dss, to run it with `DEBUG=dss*` to see the messages logged, and confirm there is an offer (`MessageType=1`) from one peer and an answer (`MessageType=2`) from the other. These shall contain some `m=video` line, and some `a=sendrecv` line below. The Unity console should show those SDP messages when received (see [here](https://github.com/microsoft/MixedReality-WebRTC/blob/de1db215f390524d5d8fd576b274c74fdcc362e2/libs/Microsoft.MixedReality.WebRTC.Unity/Assets/Microsoft.MixedReality.WebRTC.Unity/Scripts/Signaling/NodeDssSignaler.cs#L207)). ICE candidates are of little interest at this point, unless you're trying something more complex like 2 devices behind different NATs over Internet.

For info, but I doubt at this point that this is related to your problem, currently there is an issue with the UWP video capturer where remote video frames are not received from HoloLens 2 (UWP ARM) running VideoChatDemo. I couldn't reproduce that bug anywhere else, though I do not exclude this can pop up somewhere else. The symptoms are audio streaming both ways, and video only one way, with remote video from HoloLens 2 not showing up on the other peer. Early debugging shows the Media Foundation capture code on HoloLens 2 fails for some reason while trying to write the captured samples to its sink; I could not get more info so far. This is a regression from a few weeks ago where both audio and video were streaming smoothly both ways.

**Comment by eanders-MS** [comment]
Thanks for your response. Yes this is the VideoChatDemo sample Unity scene, unmodified except for adding a `Debug.Log` call to record sent signaler messages, and the addition of the `Connected` handler on `RemoteVideoSource`. The scene is running in the Unity editor, so Windows 10 Desktop, not UWP. `node-dss` is running in the background, with the `DEBUG=dss*` environment variable set.

Interesting I'm not seeing a `MessageType=2` in the log, though other signals are getting sent and received.

Unity log
https://gist.github.com/eanders-MS/3b14794f3e7d342bc3834e1a56264b00

node-dss log
https://gist.github.com/eanders-MS/77fd0d25a8ff07b027c810bcd0e44fdb

**Comment by djee-ms** [comment]
As far as that node-dss log goes, there is a single peer involved (single ID). You say you run the scene in the Unity Editor, but one can only open a single instance of that executable. Are you using 2 machines? The `NodeDssSignaler` component needs to be configured on each with the remote peer ID of the other, as seen in the node-dss logs (GET request). You might want to have a look at the docs on [configuring `NodeDssSignaler`](https://microsoft.github.io/MixedReality-WebRTC/manual/helloworld-unity-connection.html).

**Comment by eanders-MS** [comment]
I think I see now. I'd assumed I could run the local and remote video together in the same instance of Unity, but it looks like the project is set up with a single peer & signaler, able to service either the local or remote video player, but only one of them. Therefore you need two Unity player instances for it to work.

**Comment by djee-ms** [comment]
Oh right, sorry I didn't think about that. Yes [as indicated in the documentation](https://microsoft.github.io/MixedReality-WebRTC/manual/helloworld-unity-connection.html) you need 2 instances, like a real-world app.

I never considered writing a sample with 2 peer connections talking to each other in the same app, but maybe I should for simplicity? I think that's what [the webrtc.org samples](https://webrtc.github.io/samples/) are doing if I remember correctly. This is probably easier as it doesn't require any setup of `node-dss` or any other signaling solution. The drawback is that it only works within the sample, whereas the current Unity and C# samples are compatible with each other, so you can connect any mix of them together. `TestAppUWP` even deploys on HoloLens.
