### ISSUE TITLE
Hololens Video Render is Mirrored

### ISSUE THREAD

**Issue by astaikos316** [microsoft/MixedReality-WebRTC#73]
I just noticed this issue.  The video that is sent form the hololens to a peer is mirrored left to right.  Have noticed this when running with MRC turned on.

**Comment by djee-ms** [comment]
Hi @astaikos316,

Yes a couple of people reported that to me already during demos. I was under the impression this is more a matter of preference, as _e.g._ your regular laptop webcam (pointing at you) will generally be rendered mirrored for comfort, so that you see yourself like in a mirror. However the HoloLens/2 webcam is pointing away from you, so I assumed should not be mirrored.

There are multiple ways to approach that. One way would be to let the user decide, another to rely on the reported camera location (front vs. back), or a mix of both. I am not sure what's best, and how reliable the front/back information is, if at all available.

In any case for the Unity integration the rendering is done with a shader **YUVFeedShader (Unlit)** which already supports horizontal mirroring:

![image](https://user-images.githubusercontent.com/49064175/65002510-22ad8c00-d92f-11e9-8139-bc1c9c3d8c8a.png)

**Comment by fibann** [comment]
Nothing else to do here.
