### ISSUE TITLE
How to get DataChannel for json/text?

### ISSUE THREAD

**Issue by johnnyapu15** [microsoft/MixedReality-WebRTC#741]
It's easy to use for Media. I like that.

But I have to get DataChannel (like RTCDataChannel in javascript) for json communication.

How to do this?

**Comment by zxzkf1992** [comment]
I have the same needs. But don't know what to do

**Comment by zxzkf1992** [comment]
I have the same needs. But don't know how to do this :(

**Comment by ThaiVan** [comment]
Did you check out the document? [DataChannel](https://microsoft.github.io/MixedReality-WebRTC/api/Microsoft.MixedReality.WebRTC.DataChannel.html).

As what I remember, you need to create a DataChannel with necessary parameters and add it to the PeerConnection. One important thing is that the DataChannel is available unless the PeerConnection finishes negotiating. You can monitor that with the attribute DataChannel.State.

Once the DataChannel is ready, you have to convert your json text to byte[], and then send it with `SendMessage(byte[] message)`.

I do not have sample source code because I stopped working on it but I am sure it works that way.

P/S: If you can not find anythig in the documents, you should give it a try by looking it up in the library's source code. You might find out how it works, and it should have a [test case](https://github.com/microsoft/MixedReality-WebRTC/tree/master/tests/Microsoft.MixedReality.WebRTC.Tests) as well.

**Comment by zxzkf1992** [comment]
> Did you check out the document? [DataChannel](https://microsoft.github.io/MixedReality-WebRTC/api/Microsoft.MixedReality.WebRTC.DataChannel.html).
> 
> As what I remember, you need to create a DataChannel with necessary parameters and add it to the PeerConnection. One important thing is that the DataChannel is available unless the PeerConnection finishes negotiating. You can monitor that with the attribute DataChannel.State.
> 
> Once the DataChannel is ready, you have to convert your json text to byte[], and then send it with `SendMessage(byte[] message)`.
> 
> I do not have sample source code because I stopped working on it but I am sure it works that way.
> 
> P/S: If you can not find anything in the documents, you should give it a try by looking it up in the library's source code. You might find out how it works, and it should have a [test case](https://github.com/microsoft/MixedReality-WebRTC/tree/master/tests/Microsoft.MixedReality.WebRTC.Tests) as well.

Thank you for your answer, I have solved this problem
