### ISSUE TITLE
VideoChatDemo works in editor, fails in player

### ISSUE THREAD

**Issue by eanders-MS** [microsoft/MixedReality-WebRTC#82]
This might be a dupe of #77.

**Description**
The VideoChatDemo Unity scene works fine when run in the editor, but fails in standalone player with "DLL not found".

I built the Win32 and UWP variants of Microsoft.MixedReality.WebRTC.Native.dll (x86_64 only), and confirmed they were copied to the Plugins folder (to the Win32 and WSA subfolders respectively). When I run the scene in the editor, I see the webcam video feed. When I build a standalone player, I see:
```
WebRTC plugin initializing failed. See full log for exception details.
AggregationException: One or more errors occurred.
Exception: Microsoft.MixedReality.WebRTC.Native.dll
```

Also found in output_log.txt (repeats):
```
Fallback handler could not load library C:/code/Microsoft/MixedReality-WebRTC/libs/Built/Microsoft.MixedReality.WebRTC.Unity_Data/Mono/Microsoft.MixedReality.WebRTC.Native.dll
Fallback handler could not load library C:/code/Microsoft/MixedReality-WebRTC/libs/Built/Microsoft.MixedReality.WebRTC.Unity_Data/Mono/Microsoft.MixedReality.WebRTC.Native
Fallback handler could not load library C:/code/Microsoft/MixedReality-WebRTC/libs/Built/Microsoft.MixedReality.WebRTC.Unity_Data/Mono/libMicrosoft.MixedReality.WebRTC.Native.dll
```

Am I missing a step?

**Comment by djee-ms** [comment]
Did you follow the instructions related to `.meta` files in #77? Also, for context, are you using IL2CPP?

I would start by confirming whether the DLL is actually present on disk or not, to figure out if this is a problem with the deployment or the loading.

- If the DLL is not there, this is likely a Unity configuration issue with `.meta` files. You should see the DLL referenced in the list of files of the generated project.
  ![image](https://user-images.githubusercontent.com/49064175/65366655-e7c69380-dc61-11e9-81c4-0be7254550f6.png)

- If it is there, this is maybe a problem with the DLL itself (wrong architecture, etc.) or with one of its dependencies (missing dependent DLL). For the former, close Unity to avoid any sharing violation, copy manually the expected DLL, and open again. For the latter, attaching the Visual Studio debugger will tell you in the Output window which DLLs are loaded and when. If you see `Microsoft.MixedReality.WebRTC.Native.dll` loaded and immediately unloaded (or almost immediately, after a few lines of other DLLs being loaded), then that's a problem with dependent DLLs not found. Unfortunately the error message here does not provide any context. If you don't see any message, then it's the DLL which is itself not found in the first place.
  ```
  'Microsoft.MixedReality.WebRTC.Unity.exe' (Win32): Loaded 'C:\dev\mr-webrtc\libs\Microsoft.MixedReality.WebRTC.Unity\Builds\uwp_x64_pc\build\bin\x64\Debug\AppX\Microsoft.MixedReality.WebRTC.Native.dll'. Symbols loaded.
  ```

I have just tried on a branch ahead of `master`, with the UWP x64 standalone player on PC, and I have no issue loading the DLL and initializing the plugin. There is an unrelated `NullReferenceException` after when opening the local video because we dereference `Windows.Graphics.Holographic.HolographicDisplay.GetDefault()` without testing if it's non-null, but the DLL is already loaded at that point. I will fix that one.

**Comment by eanders-MS** [comment]
Yes, I was careful to revert modified dll .meta files so that export settings were preserved.

The player I referred to above is the PC/x64 standalone build with Mono scripting backend. This build doesn't export a project, it just builds an executable. The DLL is present in the output directory (in the `Microsoft.MixedReality.WebRTC.Unity_Data\Plugins subfolder`).

Oh I just tried something: When I copy the DLL to the root of the output folder (next to the executable), it works! So it's a path issue. *I can live with this workaround*.

**Comment by pablomarcos** [comment]
I had exactly the same problem and I solved also copying the dll to the root of the output folder.

**Comment by Boo0317** [comment]
> 您是否按照[＃77中](https://github.com/microsoft/MixedReality-WebRTC/issues/77)与`.meta`文件相关的说明进行操作？另外，就上下文而言，您是否使用IL2CPP？[](https://github.com/microsoft/MixedReality-WebRTC/issues/77)
> 
> 我将从确认DLL是否确实存在于磁盘上开始，以弄清这是否是部署或加载的问题。
> 
> * 如果DLL不存在，则可能是`.meta`文件的Unity配置问题。您应该在生成的项目的文件列表中看到引用的DLL。
>   ![图片](https://user-images.githubusercontent.com/49064175/65366655-e7c69380-dc61-11e9-81c4-0be7254550f6.png)
> * 如果存在，则可能是DLL本身（错误的体系结构等）或其依赖项之一（缺少依赖的DLL）引起的问题。对于前者，请关闭Unity以避免任何共享冲突，手动复制所需的DLL，然后再次打开。对于后者，附加Visual Studio调试器将在“输出”窗口中告诉您哪些DLL被加载以及何时加载。如果看到已`Microsoft.MixedReality.WebRTC.Native.dll`加载并立即被卸载（或者在加载几行其他DLL之后几乎立即被卸载），那么这就是找​​不到依赖的DLL的问题。不幸的是，这里的错误消息没有提供任何上下文。如果您没有看到任何消息，则说明它本身是DLL的第一位。
>   ```
>   'Microsoft.MixedReality.WebRTC.Unity.exe' (Win32): Loaded 'C:\dev\mr-webrtc\libs\Microsoft.MixedReality.WebRTC.Unity\Builds\uwp_x64_pc\build\bin\x64\Debug\AppX\Microsoft.MixedReality.WebRTC.Native.dll'. Symbols loaded.
>   ```
> 
> 我刚刚`master`在PC上使用UWP x64独立播放器尝试了一个分支，并且在加载DLL和初始化插件方面没有问题。`NullReferenceException`打开本地视频后，这是无关的，因为我们取消引用`Windows.Graphics.Holographic.HolographicDisplay.GetDefault()`而不测试它是否为非空，但此时DLL已经加载。我会解决的。



> Did you follow the instructions related to `.meta` files in #77? Also, for context, are you using IL2CPP?
> 
> I would start by confirming whether the DLL is actually present on disk or not, to figure out if this is a problem with the deployment or the loading.
> 
> * If the DLL is not there, this is likely a Unity configuration issue with `.meta` files. You should see the DLL referenced in the list of files of the generated project.
>   ![image](https://user-images.githubusercontent.com/49064175/65366655-e7c69380-dc61-11e9-81c4-0be7254550f6.png)
> * If it is there, this is maybe a problem with the DLL itself (wrong architecture, etc.) or with one of its dependencies (missing dependent DLL). For the former, close Unity to avoid any sharing violation, copy manually the expected DLL, and open again. For the latter, attaching the Visual Studio debugger will tell you in the Output window which DLLs are loaded and when. If you see `Microsoft.MixedReality.WebRTC.Native.dll` loaded and immediately unloaded (or almost immediately, after a few lines of other DLLs being loaded), then that's a problem with dependent DLLs not found. Unfortunately the error message here does not provide any context. If you don't see any message, then it's the DLL which is itself not found in the first place.
>   ```
>   'Microsoft.MixedReality.WebRTC.Unity.exe' (Win32): Loaded 'C:\dev\mr-webrtc\libs\Microsoft.MixedReality.WebRTC.Unity\Builds\uwp_x64_pc\build\bin\x64\Debug\AppX\Microsoft.MixedReality.WebRTC.Native.dll'. Symbols loaded.
>   ```
> 
> I have just tried on a branch ahead of `master`, with the UWP x64 standalone player on PC, and I have no issue loading the DLL and initializing the plugin. There is an unrelated `NullReferenceException` after when opening the local video because we dereference `Windows.Graphics.Holographic.HolographicDisplay.GetDefault()` without testing if it's non-null, but the DLL is already loaded at that point. I will fix that one.

In my case, Microsoft.MixedReality.WebRTC.Native.dll loaded and immediately unloaded ,TWICE 
![1570707142(1)](https://user-images.githubusercontent.com/33243304/66565432-09e27000-eb95-11e9-88b5-63de1cc89240.jpg),and Throw an Exception. I run it on HL1.
 How can I solve it?

**Comment by djee-ms** [comment]
This generally means that one of the dependencies is missing on the device. Normally all dependent DLLs should have been deployed by Visual Studio though. You can browse the list of dependencies with [Dependencies](https://github.com/lucasg/Dependencies) for example, and see if any one is missing on the device.
