### ISSUE TITLE
Get media track details (resolution and aspect ratio)

### ISSUE THREAD

**Issue by eanders-MS** [microsoft/MixedReality-WebRTC#85]
Hi. Is it possible to get the details of the remote video track added? The underlying MediaStreamTrack allows access to these settings, as per https://w3c.github.io/mediacapture-main/#dom-mediatracksettings.

Context: In Unity, when the remote video stream starts playing, I need to size the MediaPlayer's quad to match the aspect ratio, which can vary depending on the source video settings. Perhaps there's another way to do this?

**Comment by djee-ms** [comment]
The link you are referencing is a JavaScript API to capture videos, not a WebRTC one. There is no such thing as `MediaStreamSettings` in the WebRTC 1.0 standard, so it's not available in C++.

Surprisingly, there is currently no API that I know of which gives any information about the remote track. The only way is to get the frame size from the first callback invoke and lazily setup anything you want from there. This is what `TestAppUWP` is doing with its call to `CreateVideoStreamSource()`:
https://github.com/microsoft/MixedReality-WebRTC/blob/a2a3c9ff7109567a1f5945b33ab3ca3aab94f423/examples/TestAppUwp/MainPage.xaml.cs#L979-L1003

We discussed adding an event for that (can't find the discussion again sorry), that would be doing that work internally and expose some event like `VideoResized` or similar, but that is mostly for convenience, wrapping over that lazy check in the frame callback.

I am happy to change that if someone shows me an API somewhere that actually gives those info when the track is added. But `webrtc::PeerConnectionObserver::OnAddTrack()` currently only gives the `webrtc::RtpReceiverInterface`, which doesn't contain much information. And this is understandable, since the video resolution can change during the session, so providing a resolution when the track is added is meaningless. In fact, I am not even sure the RTP layer can know the resolution until the first frame is received and possibly even decoded; see [this comment](https://github.com/webrtc-uwp/webrtc-windows/pull/65#discussion_r327677589):
> In our case, frame dimensions were absent from the packet headers when using the Multiplex WebRTC protocol to send H264 frames.

**Comment by eanders-MS** [comment]
@djee-ms Thanks for the detailed response. Reading width/height from the first video frame and lazily initializing things from there is a perfectly acceptable solution for my purpose. I should have thought of that myself :)

**Comment by djee-ms** [comment]
I think an explicit event would still be more convenient. I'll see to add one later.
